### ISSUE TITLE
Publishing to Compute Engine Deletes folders/files

### ISSUE THREAD

**Issue by scgough** [GoogleCloudPlatform/google-cloud-visualstudio#1020]
I have a project I publish from my local machine to my Windows Compute Engine instance. 
I'm publishing via Visual Studio 2015

The 'live' site has a folder of assets on the server which contain images uploaded by users from within the site. 

Locally, this folder is not mirrored in VS. 

When I publish, the folder on the live server is deleted/mutated to mirror the local version. 

I want the Publish to ignore this folder as the 'live' version of it should remain untouched. 

I've tried excluding the folder from the local project but this just results in the live folder being completely deleted when I publish.

**Comment by ILMTitan** [comment]
@scgough Thank you for your feedback. The next release will change the Windows VM deploy process to call MSBuild. You will be able to make the changes described by [this stackoverflow answer](https://stackoverflow.com/a/32729801/143069) in your build file to exclude the desired folder.
