### ISSUE TITLE
 GoogleCloudToolbar extension on VS2017 stopped working

### ISSUE THREAD

**Issue by YingGCP** [GoogleCloudPlatform/google-cloud-visualstudio#1064]
An user have installed the GoogleCloudToolbar extension on VS2017. It was working fine until one day it started throwing the below error. This error pops up as soon as I open VS.

"The 'GoogleCloudExtensionPackage' package did not load correctly.

The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'xxxxxx/ActivityLog.xml'

Restarting Visual Studio could help resolve the issue"

The user uninstalled all other extensions that he downloaded, reinstalled googlecloud ext, resinstalled VS, repaired. Nothing fixed the issue. 'Publish to google cloud' option is disabled. Clicking on any other options like 'Manage Accounts' under GoogleCloud toolbar opens the same error pop up.

The ActivityLog is attached: 
[ActivityLog.txt](https://github.com/GoogleCloudPlatform/google-cloud-visualstudio/files/2306957/ActivityLog.txt)

**Comment by YingGCP** [comment]
Here's some additional information if needed:

- Precise version of Windows
Windows 10 Pro Version 1803

- Precise version of Visual Studio,including updates (Help / About screenshot works)
Microsoft Visual Studio Professional 2017 
Version 15.8.0
VisualStudio.15.Release/15.8.0+28010.0
Microsoft .NET Framework
Version 4.7.03056

- Version of Google Cloud Tools extension
Version 1.4.0.0

- Authentication state in the plugin
Unable to check because Manage account option is shown as disabled

- Reproduction scenario
Unfortunately I don't know. It was working fine and one day an error started popping up as soon as I open VS. Also when I select any options in the cloud toolbar.

- Exact result with screenshots of any error messages
screenshots attached
![clouderror](https://user-images.githubusercontent.com/42581187/44415506-9ddf1b80-a53e-11e8-8e5a-f724248e4d74.png)
![toolbar](https://user-images.githubusercontent.com/42581187/44415522-a899b080-a53e-11e8-8ec7-48d025b111dd.png)

**Comment by YingGCP** [comment]
The VS detailed version information.
[VS_Help_About_Info.txt](https://github.com/GoogleCloudPlatform/google-cloud-visualstudio/files/2307180/VS_Help_About_Info.txt)

**Comment by ILMTitan** [comment]
Thank you so much for including the Activity log.  It looks like, somehow, one of your user accounts has multiple account user account files.

Go to _%LOCALAPPDATA%\googlecloudvsextension\accounts_ and you will find several *.json files. Deleting them all should fix this issue.

At least two of those *.json files have the same `"account":"<user-email>"` field.

**Comment by ILMTitan** [comment]
I am opening #1065 to track a fix for the underlying bug.

**Comment by reshmakishore** [comment]
Thanks. The above fix worked. There were 2 *.json files in the folder and it started working when I deleted both of them.

**Comment by ILMTitan** [comment]
Glad to hear you are about to use the extension again.
