### ISSUE TITLE
Deploying .Net to Compute defaults to x86?

### ISSUE THREAD

**Issue by NPSF3000** [GoogleCloudPlatform/google-cloud-visualstudio#1067]
Been using the VS tools plugin 2.0.0.0 to deploy code to GCP.  Recently a project started failing to deploy, and it appears it's because the build command from GCP tools is defaulting to x86 instead of 'Any CPU'.

Editing my project fixed this for now:

```
FROM  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
TO     <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU' Or '$(Configuration)|$(Platform)' == 'Release|x86'">
```

Possible fixes:
A) Default to AnyCPU
B)  Default to whatever the project is already selected as.
C) Add a drop-down option in the deploy UI?

**Comment by ILMTitan** [comment]
The version 1.4.0 was explicitly stating a `Platform` of `AnyCPU`, while version 2.0.0 does not.
I would be curious to see what part of the project file was setting the `Platform` to `x86`.
I will have to consider if/how we change this again.

**Comment by NPSF3000** [comment]
@ILMTitan I wish I knew.  Did a grepWin on the project for x86 and wasn't able to figure out why it was defaulting to this.

**Comment by ILMTitan** [comment]
@NPSF3000

The solution I am currently considering is adding a new property `GoogleComputeEngineBuild` that I will set to `True` when running a build from the extension. You could then add the following code to your build file:
```
<PropertyGroup Condition="$(GoogleComputeEngineBuild) == 'True'">
    <Platform>AnyCPU</Platform>
</PropertyGroup>
```

Would that be sufficient for to fix your problem?
