### ISSUE TITLE
Error deploying to container engine

### ISSUE THREAD

**Issue by mitulpanch** [GoogleCloudPlatform/google-cloud-visualstudio#1068]
Deploying Project.Api to Kubernetes Engine
dotnet publish -o "C:\Users\User\AppData\Local\Temp\il5vee3z.zjf" -c Release
Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

ERROR: (gcloud.container.builds.submit) This command has been replaced with `gcloud builds`.
Failed to deploy Project.Api to Kubernetes Engine

Cloud API Version : 225.0.0

**Comment by ILMTitan** [comment]
Closed in #1069
