### ISSUE TITLE
Stackdriver Debugging GKE

### ISSUE THREAD

**Issue by HStuart18** [GoogleCloudPlatform/google-cloud-visualstudio#1075]
So I am trying to enable Stackdriver Debugging with my ASP.NET Core application in Visual Studio 2017. I haven't created any PDB files myself, rather am just assuming the the ones Visual Studio produce will suffice (correct me if I'm wrong). Within VS GUI, I generated a Dockerfile and edited it to be:

    FROM gcr.io/dotnet-debugger/aspnetcore:2.0
    COPY . /app
    WORKDIR /app
    ENV STACKDRIVER_DEBUGGER_MODULE=module
    ENV STACKDRIVER_DEBUGGER_VERSION=1
    ENTRYPOINT ["/usr/share/dotnet-debugger/start-debugger.sh","dotnet", "telebot-pianomoves-v1.dll"]
Through Google Cloud Tools for VS, I published my application to a Google Kubernetes Engine cluster that had sufficient authorisation scopes. I also enabled the API in the GCP console.

When I opened the Stackdriver Debugging interface, it did seem to recognise my application as module-1. So I proceeded by uploading my local source code (specifially, the folder that contained my VS solution). The problem, is that when I click on a line to add a logpoint, the console shows Log points are currently not supported. and when I press on a line to add a snapshot, the console shows Waiting for snapshot to hit... and stays like that indefinitely.

Also, the API metrics console says that I am receving both 200 and 499 response codes.

Are these issues likely to arise from a problem with uploading source code? Is it my Dockerfile? PDB file? I can try and provide more specific information if it would help, but I didn't want to clog up the post with screenshots and I am hoping what is here is enough for someone to give me some direction.

Thank you so much!

***This is a post I made on Stackoverflow and was advised on raising an issue here on GitHub.

**Comment by iantalarico** [comment]
@HStuart18 This sounds like it may be an issue with the debugger.  Do you mind closing this issue here and opening one in the repo for the [debugger](https://github.com/GoogleCloudPlatform/google-cloud-dotnet-debugger)?  I'm happy to give you a hand over there.  We recently fixed some bugs in the debugger and should be doing a release soon but we can dig into the issue more in the other repo.

**Comment by HStuart18** [comment]
Hi Ian,

I will close the issue now and re-open it in the Debugger repo. Thanks for the help!
