### ISSUE TITLE
Visual Studio 2019 Support

### ISSUE THREAD

**Issue by mitulpanch** [GoogleCloudPlatform/google-cloud-visualstudio#1087]

**Comment by lerudiconsulting** [comment]
Is there any indication of the progress on this? Google Cloud tools are something I use on a daily basis. Very excited and interested to get any indication of progress.

**Comment by DDzia** [comment]
Same question. Any progress?

**Comment by PekitP** [comment]
Checked the issue with GCP support, but they could not produce an anwer..

**Comment by iantalarico** [comment]
Thank you all for the feedback and interest, we currently a little short on resources but will try and get to this soon.  I will follow up shortly when I have a better answer, thank you for your patience!

**Comment by lerudiconsulting** [comment]
> Thank you all for the feedback and interest, we currently a little short on resources but will try and get to this soon. I will follow up shortly when I have a better answer, thank you for your patience!

Thanks for the feedback! I appreciate it a lot. Right now I am bouncing between VS 2017 and VS 2019 mainly because of this missing feature, and it would be great to go full on VS 2019.

**Comment by creativeavatar** [comment]
Any updates on this? I noticed several commits were made yesterday in regards to fixes for VS2019. I tried the latest release via the appveyor seeing if maybe it was all fixed now, but it didn't work.

**Comment by iantalarico** [comment]
@creativeavatar We are currently working on this but are a little short handed, hopefully we will get something out the door soon.

**Comment by s-richter** [comment]
Any updates on that? 

Trying the method on [https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/](https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/) doesn't seem to work.

Using the Extension Manager 2017 / 2019 [https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ExtensionManager2019](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ExtensionManager2019) also doesn't seem to work.

I´ve never tried to manipulate VS Extensions before, so maybe I´m overlooking another possibility?

**Comment by meteatamel** [comment]
@s-richter I sent a [PR](https://github.com/GoogleCloudPlatform/google-cloud-visualstudio/pull/1093) to fix the project for Visual Studio 2017/2019 and after that, I can debug the extension within 2019. 

Do you want to check the [artifact](https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-visualstudio/builds/27471892/artifacts) built from my PR to see if it works on your Visual Studio 2019 and report back?

**Comment by meteatamel** [comment]
The latest release (2.0.3) now supports VS 2019.
