### ISSUE TITLE
Error Showing Google Cloud Repositories In Vs2017 and 2019

### ISSUE THREAD

**Issue by juanfer007** [GoogleCloudPlatform/google-cloud-visualstudio#1096]
Google Cloud repositories noth showing list in Team Explorer. 
I'm logged correctly, but it shows the next exception:

Error persists in VS2017 and  vs2019

`System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à GoogleCloudExtension.Analytics.AnalyticsEvent.GetMetadataFromParams(String[] args)
   à GoogleCloudExtension.CloudSourceRepositories.CsrSectionControlViewModel.GoogleCloudExtension.TeamExplorerExtension.ISectionViewModel.Initialize(ITeamExplorerUtils teamExplorerService)
   à GoogleCloudExtension.TeamExplorerExtension.Section.Microsoft.TeamFoundation.Controls.ITeamExplorerSection.Initialize(Object sender, SectionInitializeEventArgs e)
   à Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)`

![image](https://user-images.githubusercontent.com/6095396/66091872-8fdc3680-e557-11e9-8c8a-a91048b21209.png)

**Comment by quoctruong** [comment]
@meteatamel It seems like on this [line](https://github.com/GoogleCloudPlatform/google-cloud-visualstudio/blob/master/GoogleCloudExtension/GoogleCloudExtension/CloudSourceRepositories/CsrSectionControlViewModel.cs#L147), we are trying to report analytics event but `GoogleCloudExtensionPackage.Instance` was not yet initialized (so it was null).

**Comment by meteatamel** [comment]
What are the repro steps to see this error? It happens all the time?

**Comment by quoctruong** [comment]
@meteatamel Simply open Team Explorer with the extension and it will show the error.

**Comment by meteatamel** [comment]
This should be fixed now in the latest release 2.0.4. Please try out and let us know if you encounter other issues.
