### ISSUE TITLE
Visual Studio 2022 Version 17.x not supported

### ISSUE THREAD

**Issue by addisonvex** [GoogleCloudPlatform/google-cloud-visualstudio#1117]
Having added the Google Cloud Tools for Visual Studio Extension v2.0.4.0 to Visual Studio 2022 v17.1.0, creating a new ASP.NET Core on Google Cloud Platform project results in a dialog simply stating, "Version 17.0 is not supported".

![image](https://user-images.githubusercontent.com/39273307/155421272-9f30cd0a-5a5b-46e7-ae32-e3e9e0718eed.png)

**Comment by jskeet** [comment]
I'm afraid the Visual Studio extension is no longer supported or maintained, and there are no current plans to support VS2022.

**Comment by jskeet** [comment]
(I've just seen that there *was* some effort 5 months ago, but I'm afraid I don't think there are any plans at the moment.)
