### ISSUE TITLE
Latest kubectl version dropped --replicas flag. Deployments failing

### ISSUE THREAD

**Issue by baileyst** [GoogleCloudPlatform/google-cloud-visualstudio#1120]
Good Day,

We have noticed after upgrading kubectl that deployments are failing. I suspect this is due to the dialog box that pops up with the replicas option when you click deploy to cloud. After looking at the source code we noticed when you click publish, a kubectl command is ran in the back end with the --replicas flag and since it has been dropped in the later versions of kubectl deployments are failing. We worked around this by replacing the kubectl.exe with an older version.

Is it possible to update the visual studio extension to accommodate these changes made in the newer versions of kubectl? Is an updated plugin in the works?

Regards,

**Comment by jskeet** [comment]
I'm afraid the Visual Studio extension is no longer supported or maintained.
