### ISSUE TITLE
Put project templates in the Web and Cloud nodes as well

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-visualstudio#113]
Seems like this is the place where people might expect them

**Comment by ivannaranjo** [comment]
The nodes are based on the location of the templates in the final package. To have them in more than one place will mean duplicating the templates in the package. Will investigate more.

**Comment by ivannaranjo** [comment]
// cc: @csells 
It seems that having our own category "Google Cloud Platform" should be sufficient.
