### ISSUE TITLE
We should integrate CSR direction into VS

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-visualstudio#123]
The current process for manually generating credentials and plugging those into VS is a long and tortuous one.

**Comment by ivannaranjo** [comment]
Thinking about having a feature to manage credentials for VMs and cache them locally.

**Comment by ivannaranjo** [comment]
This bug is tracking adding integration of Cloud Source Repositories into VS. The fact that I thought it was referring to VM credentials was my own doing :).

Definitely should be able to wrap `gcloud source` to create local repos. VS should just work after that.

**Comment by ivannaranjo** [comment]
This should probably be another node in the Cloud Explorer, with the source repos associated with the current project.

**Comment by ivannaranjo** [comment]
Can use `gcloud alpha source repos list --format=json` to list the repos available in the current project.

Probably should wait until the `source repos list` command moves out of alpha.
