### ISSUE TITLE
Have a way to hide empty zones in Compute Engine list

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/google-cloud-visualstudio#129]
In Compute Engine list, all the zones are listed, if they are empty (no VMs in that zone). There should be a way to control this, I shouldn't have to see all the zones by default, I usually only care about 1 or 2 zones.

**Comment by ivannaranjo** [comment]
I agree, will produce the list of zones that contains VMs. The user will be able to choose the right zone in the new create VM dialog.

**Comment by ivannaranjo** [comment]
This is being tracked in #166

**Comment by ivannaranjo** [comment]
This is now fixed in  1b5ba6f
