### ISSUE TITLE
"Open Terminal Session" should direct me to create a username/password

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/google-cloud-visualstudio#134]
I select the Windows instance and try “Open Terminal Server Session”. It’s asking me username/password. I have no idea what username/password I’m supposed to use. Now, I see a “Create or Reset Password” in the same menu, so I guess that I actually need to create a username/password. I don’t like this, I shouldn’t have to guess. “Open Terminal Server Session” should be grayed out until I create a password, or it should direct me to create a password.

**Comment by ivannaranjo** [comment]
Thinking about keeping a cache of user accounts stored in the developer machine, similar to the google account manager.

**Comment by ivannaranjo** [comment]
See PR #169, by storing the credentials we can offer the choice later on when starting a Terminal server window. The extension can create an .rdp file using the credentials chosen, and open a new session using that .rdp file.

If no credentials are found we can prompt the user to create them.

**Comment by ivannaranjo** [comment]
This is now in.
