### ISSUE TITLE
Google Cloud Storage list is not per zone

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/google-cloud-visualstudio#136]
Google Compute Engine list is per zone, whereas Google Cloud Storage list is not. I find this inconsistent.

**Comment by ivannaranjo** [comment]
Working on a solution for this, allowing the user to pivot between zones and instances. Or simply just listing the instances.

**Comment by ivannaranjo** [comment]
This is tracked by #165

**Comment by ivannaranjo** [comment]
This is checked in with  66e8df5
