### ISSUE TITLE
List buckets within Visual Studio

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/google-cloud-visualstudio#137]
Currently, you can only see bucket names in Google Cloud Storage. I should be able to see bucket contents as well from Visual Studio.

**Comment by ivannaranjo** [comment]
This feature has be thought with care, there can be an impossibly large number of file stored in a bucket, and the UI can be incredibly polluted with this. Some basic browsing, followed by custom dedicated UI is probably the way to go.

**Comment by ivannaranjo** [comment]
This is the GCS browsing work.
