### ISSUE TITLE
copy bucket uri feature in context menu

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-visualstudio#143]
It seems like many gsutil commands require a uri as a parameter to point to a particular files in GCS. It would help to be able to get at least the root gs:// address in the Cloud Explorer

**Comment by ivannaranjo** [comment]
Not yet, there's a feature request on this, [#309](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/309). For now the path would only be useful on the CLI.

Some APIs do use the gs:// path (the Vision API for example) but that is not as common.

**Comment by ivannaranjo** [comment]
The GCS browser is going to show the gs:// path on the properties window when selecting a file in GCS.
