### ISSUE TITLE
Users expect their Google Cloud credentials to be usable to deploy to the ASP.NET instance

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#149]
What possible solutions have we considered?

**Comment by ivannaranjo** [comment]
The core issue at hand here is that the Google credentials of the developer do not apply to the credentials of the Windows VM created in GCE. They are completely disconnected. The user needs to create a new set of credentials to access the VM, including deployment.

As for your question, the only alternative that we have considered is to paper over it by automating as much as possible the creation of a set of credentials used for deployment.

**Comment by chrsmith** [comment]
I assume AWS and Azure have the same problem?

**Comment by ivannaranjo** [comment]
See PR #169 as a form of mitigation. Trying to make the credentials look more like the SSH keys that are autogenerated for GCE Linux users and less like Windows accounts. That PR is the foundation, features needing Windows credentials should be able to query the stored credentials. For deployment for example we should be able to use one of the stored credentials in our custom dialog.

**Comment by ivannaranjo** [comment]
Azure has exactly the same issue for VMs with only "Local Accounts" created, but they do have the advantage of having Domain joined VMs available.

The fact that we now generate .rdp files from your cached credentials means that the user doesn't need to see the password prompt anymore.
