### ISSUE TITLE
I don't know what to do when I see the "Choose Credentials" dialog.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#188]
![choose credentials](https://cloud.githubusercontent.com/assets/11778530/18490934/0a513e5a-79b9-11e6-95bd-640d136a378e.png)

Do I click OK?  Or do I click Cancel?  I have no idea what the "..." button does.  Speaking of which, why does "No credentials found" end with "..."?

I figured it out, but it did make me stop and think for about 10 seconds.

**Comment by hray2003** [comment]
@ivannaranjo This is what we were just talking about.

1. If user has to have a credential to move forward, and there's no credential found, then the "OK" button should be grey, while "Cancel" button enabled. 
2. Perhaps we could consider replace the "..." button with text under the drop down menu, which prompts user to create new credential. In this way the trigger for user to take action is not hidden. 
3. Once new credential is created, I assume user will be able to see that in the drop down and move on by clicking ok?

**Comment by ivannaranjo** [comment]
Agreed, the metaphore of the "..." button was not the best. I think that the "<Create new user...>" entry in the drop down is probably more understandable.

**Comment by ivannaranjo** [comment]
This is hopefully now fixed, as we have the link to open the manage credentials dialog.
<img width="303" alt="screen shot 2016-10-04 at 2 36 38 pm" src="https://cloud.githubusercontent.com/assets/9807532/19193315/87daa118-8ca1-11e6-900a-b4d45941c3c8.png">
