### ISSUE TITLE
Reset credentials keeps crashing VS

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-visualstudio#190]
Trying to add a new user to the Windows Credentials (plugin release v0.9.2.1-q3_master)
After saying yes to reset password:
<img width="590" alt="screen shot 2016-09-16 at 9 48 09 am" src="https://cloud.githubusercontent.com/assets/1758462/18594285/009f252e-7bf4-11e6-8bcd-08e3c5251423.png">

VS crashes
<img width="590" alt="screen shot 2016-09-16 at 9 48 09 am" src="https://cloud.githubusercontent.com/assets/1758462/18594289/0440dbd2-7bf4-11e6-85e8-06d267374062.png">

I verified that the VM was up and running (I RDPed into it first)

I launched the debugger, and this is what it gives me:

```
System.Reflection.TargetInvocationException was unhandled
Message: An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
Additional information: Exception has been thrown by the target of an invocation.
```

**Comment by ivannaranjo** [comment]
Crud... Can you provide the output of `gcloud info` to see if that is the problem?

This is related to #198, the extension should never cause VS to crash.

**Comment by ivannaranjo** [comment]
This shoud not happen anymore.
