### ISSUE TITLE
Provide About... in Cloud Tools menu

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-visualstudio#191]
To allow to verify plugin version, especially useful for testing (verify you have installed the latest)

**Comment by ivannaranjo** [comment]
This is done via the "Tools > Extensions and Updates" dialog, in there you can see the version of all plug-ins installed.
<img width="955" alt="screen shot 2016-09-27 at 3 09 31 pm" src="https://cloud.githubusercontent.com/assets/9807532/18877218/6dd35790-84c4-11e6-8603-da7a538ce367.png">
