### ISSUE TITLE
Dialog name is Reset password when action is Add Credential

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-visualstudio#192]
When pressing on Add Credential, the name of the dialog is Reset Password.

<img width="514" alt="screen shot 2016-09-16 at 9 47 18 am" src="https://cloud.githubusercontent.com/assets/1758462/18594418/c194da94-7bf4-11e6-9c36-ce189fb743fa.png">

<img width="457" alt="screen shot 2016-09-16 at 9 47 26 am" src="https://cloud.githubusercontent.com/assets/1758462/18594427/ceb7a756-7bf4-11e6-8e5c-76080d147aad.png">

**Comment by chrsmith** [comment]
Also, from the image, the Reset Password dialog's text box appears to be multi-line? Either that or the cursor doesn't appear to be in the right place.

**Comment by ivannaranjo** [comment]
Will fix the UI.

**Comment by ivannaranjo** [comment]
This is now fixed in q3_master.
