### ISSUE TITLE
Confusing dialog state in Reset password

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-visualstudio#194]
<img width="411" alt="screen shot 2016-09-16 at 9 47 48 am" src="https://cloud.githubusercontent.com/assets/1758462/18594488/394f9cea-7bf5-11e6-86c7-14a7d420d199.png">

It is not clear if the buttons can be clicked. If they can be clicked, it's not clear what pressing either would do. Consider showing progress bar and the buttons clearly disabled.

**Comment by ivannaranjo** [comment]
The buttons are disabled, the theming clearly is confusing. Changing to have an indeterminate progress bar is probably the best way.

**Comment by ivannaranjo** [comment]
This is now fixed with the new look. We show a progress bar:
![progressstate](https://cloud.githubusercontent.com/assets/9807532/19190156/d1ec6bc8-8c93-11e6-82a9-389b7233de42.png)
