### ISSUE TITLE
Extension crashes after publishing to GAE Flex

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-visualstudio#197]
After installing a newish build of the extension (not sure of the build date), the extension crashes after publishing to GAE.

The publish proceeds (slowly!) as you would expect. However, once the publish completes, Visual Studio crashes. (The callstack when you try to debug it is purely in Win32/kernel land.) However, looking at appspot.com the application is deployed. So the crash is probably very late in the process, perhaps during a cleanup step?

"System cannot find the file specified"
````
>	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ThrowAsync.AnonymousMethod__6_0(object state)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unknown
````

Link to the version of the extension version I am running:
https://ci.appveyor.com/api/buildjobs/klj0ctgjy51072kc/artifacts/GoogleCloudExtension%2FGoogleCloudExtension%2Fbin%2FRelease%2FGoogleCloudExtension.vsix

Since the app is deployed, I am not blocked by this. So no need to thrash in fixing this.

**Comment by ivannaranjo** [comment]
This is the Achilles hill of async programming, the callstacks are awful.  This could be very well a failure during cleanup but the exceptions are handled. I need to repro it.

**Comment by ivannaranjo** [comment]
This should not happen again after the hardened exception handler work.
