### ISSUE TITLE
"The Google Compute Engine API is not enabled for this project"

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-visualstudio#204]
If I create a new project in pantheon and then open it with VS to create a new VM, I'm told that the GCE API is not enabled for this project. Can we just handle that for them? Or provide a link that does it? Or some docs? Or something?

**Comment by csells** [comment]
Right-clicking on the error message provides an Enable API link -- can we just do it for them? If I create a VM in pantheon, I don't have to enable the API separately.

**Comment by ivannaranjo** [comment]
I think that now we can enable APIs, will be looking into this.

**Comment by ivannaranjo** [comment]
We should look to checking API states, and offering up to enable, if necessary.
