### ISSUE TITLE
Building a project from the Google ASP.NET MVC 4 template fails.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#212]
I created a new project from the template, tried building, and see this error;
Severity    Code    Description Project File    Line    Suppression State
Error       This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Net.Compilers.1.0.0\build\Microsoft.Net.Compilers.props.    GoogleAspNetMvc1    c:\users\rennie\documents\visual studio 2015\Projects\GoogleAspNetMvc1\GoogleAspNetMvc1.csproj  281

**Comment by ivannaranjo** [comment]
Did you configure NuGet on that machine? Ensure that the sources enabled and that you tick the "Allow NuGet to download missing packages" checkbox in the "Tools > NuGet Package Manager > Package Manager Settings" dialog.

**Comment by SurferJeffAtGoogle** [comment]
Seeing this again:

PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "c:\users\jeffrey rennie\documents\visual studio 2015\Projects\GoogleAspNetCoreMvc2\.vs\restore.dg" -s "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages"
log  : Restoring packages for c:\users\jeffrey rennie\documents\visual studio 2015\Projects\GoogleAspNetCoreMvc2\project.json...
error: Unable to resolve 'Google.Cloud.Diagnostics.AspNetCore (>= 1.0.0-alpha04)' for '.NETCoreApp,Version=v1.0'.
log  : Restoring packages for tool 'BundlerMinifier.Core' in c:\users\jeffrey rennie\documents\visual studio 2015\Projects\GoogleAspNetCoreMvc2\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in c:\users\jeffrey rennie\documents\visual studio 2015\Projects\GoogleAspNetCoreMvc2\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in c:\users\jeffrey rennie\documents\visual studio 2015\Projects\GoogleAspNetCoreMvc2\project.json...
log  : Writing lock file to disk. Path: c:\users\jeffrey rennie\documents\visual studio 2015\Projects\GoogleAspNetCoreMvc2\project.lock.json
log  : c:\users\jeffrey rennie\documents\visual studio 2015\Projects\GoogleAspNetCoreMvc2\GoogleAspNetCoreMvc2.xproj
log  : Restore failed in 15001ms.
Errors in c:\users\jeffrey rennie\documents\visual studio 2015\Projects\GoogleAspNetCoreMvc2\GoogleAspNetCoreMvc2.xproj
    Unable to resolve 'Google.Cloud.Diagnostics.AspNetCore (>= 1.0.0-alpha04)' for '.NETCoreApp,Version=v1.0'.

Yes, Nuget is fully configured to download missing nuget packages.

**Comment by ivannaranjo** [comment]
Can you try again? I have seen this failures before when working from clean machines, where the packages are not yet cached. These are typically transient errors on NuGet where a package cannot be found. The package is available [here](https://www.nuget.org/packages/Google.Cloud.Diagnostics.AspNetCore/1.0.0-alpha04) so the build will succeed if the restore step finalizes correctly.

**Comment by SurferJeffAtGoogle** [comment]
Tried again, and the build succeeded.
