### ISSUE TITLE
Multi-page dialog boxes for a sequence of related actions/results

### ISSUE THREAD

**Issue by hray2003** [GoogleCloudPlatform/google-cloud-visualstudio#242]
Could we consider using multi-page dialog boxes for a sequence of related actions/results, so that user will not see stack of dialogs? I can help with design for that.

> Multi-page dialog boxes
> Use a multi-page dialog box instead of individual dialog boxes when you have the following sequence of related pages:
> A single input page (optional)
> A progress page
> A single results page

<img width="541" alt="screen shot 2016-10-13 at 10 53 35 am" src="https://cloud.githubusercontent.com/assets/7425725/19360468/9ac98f00-9133-11e6-8995-4ad04955e441.png">
<img width="518" alt="screen shot 2016-10-13 at 10 53 50 am" src="https://cloud.githubusercontent.com/assets/7425725/19360474/9d84b1c0-9133-11e6-89f1-11485573b8cd.png">
<img width="529" alt="screen shot 2016-10-13 at 10 53 55 am" src="https://cloud.githubusercontent.com/assets/7425725/19360478/a0bddbbe-9133-11e6-858f-e9ae02602449.png">
<img width="534" alt="screen shot 2016-10-13 at 10 54 08 am" src="https://cloud.githubusercontent.com/assets/7425725/19360499/c2fe8afc-9133-11e6-99cc-f509fcafd426.png">

**Comment by ivannaranjo** [comment]
Hey Rui, this would be a good idea. Transform these into a wizard like dialog. Let me know if you need anything special to start a mockup on how this would look.
