### ISSUE TITLE
VS seems to take a lot longer to load with the GCP plugin installed

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-visualstudio#269]
It used to start pretty quickly; now it takes minutes.

**Comment by ivannaranjo** [comment]
That doesn't happen on any of my test machines. If you can see the cloud explorer that means the extension is already loaded and ready to use, and it is not doing anything until to expand/collapse nodes. There's something else afoot here.

Please run VS with the /Log command line so we can see what is going on on your machine.

**Comment by csells** [comment]
Now that I’m using /log, VS is starting much more quickly. I’ll keep an eye on it during my test.

**Comment by ivannaranjo** [comment]
I'm closing for now, if you encounter this issue again please re-open.
