### ISSUE TITLE
Text cut off in dialog.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#275]
![image](https://cloud.githubusercontent.com/assets/11778530/20189824/aceaf9e2-a733-11e6-87d6-f8b440064f97.png)

**Comment by ivannaranjo** [comment]
What version of the extension are you using the, new dialog has a slightly different layout and it grows dynamically:

<img width="317" alt="screen shot 2016-11-14 at 11 30 50 am" src="https://cloud.githubusercontent.com/assets/9807532/20263317/06de3f86-aa5e-11e6-8510-302f57a8293f.png">

**Comment by SurferJeffAtGoogle** [comment]
I'm using version 0.9.4.0

**Comment by ivannaranjo** [comment]
This should be version 1.0.0.0. Which is the [RC build](https://ci.appveyor.com/api/buildjobs/ukpnbo26v5evfpwl/artifacts/GoogleCloudExtension%2FGoogleCloudExtension%2Fbin%2FRelease%2FGoogleCloudExtension.vsix). Try there.
