### ISSUE TITLE
Windows Credentials dialog doesn't have an Edit credentials button

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-visualstudio#278]
As a user, how to I change a password for an existing set of credentials?

**Comment by ivannaranjo** [comment]
Delete and create a new one. We're going to need a new dialog for editing. Let me work with the designers to see if we can adapt the existing "Add new credentials" dialog for this.

Do you think that this is a GA blocker?

**Comment by ivannaranjo** [comment]
I'm closing for now, if you think that this is a GA blocker, lets re-open and discuss.
