### ISSUE TITLE
Use the built-in toolbar control for the "toolbar" in the Cloud Exlorer

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-visualstudio#319]
Use the the built-in toolbar for tool windows in Visual Studio which is described [here](https://msdn.microsoft.com/en-gb/library/bb164714.aspx) instead of the home grown one. It will look exactly right instead of trying to duplicate the functionality.

**Comment by ILMTitan** [comment]
I don't think this affects user experience at all, and so will not be done.
