### ISSUE TITLE
Manage Authorized Networks,  Add 'Pending save' or 'Pending Deletion' 

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#321]
In the list of to-be-added or to-be-saved 'networks' , it would be great if we can distinguish what is already saved , what is newly added. 

See the screenshots below.  I can't tell that first item is already saved and the second item is to be saved.

![manage-authorized-networks-pending-save-or-deleteion](https://cloud.githubusercontent.com/assets/22829476/20734777/8df8ae68-b650-11e6-859a-111c76360861.PNG)

**Comment by ivannaranjo** [comment]
Why do you need to know what changes are "pending"? This UI needs to be revised to add buttons outside of the items, etc.. but the same premise stays. You are editing a list, no need to show all of the changes.

**Comment by Deren-Liao** [comment]
This list mixes up what have been saved + to be saved.   The question would be like " What do I get if I click Cancel button" ?
