### ISSUE TITLE
Manage Authorization Networks fail if user updated it on Cloud Console at the same time

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#322]
I would say this is corner case. 
I am trying to add / remove "authorization networks" at VS extension.
Before saving the networks, I went to Cloud Console and added or deleted an authorization networks. 
Then, I came back to VS and click 'Save'. 
An error happens with hard to understand messages.
![cloud-sql-add-network-error](https://cloud.githubusercontent.com/assets/22829476/20734886/43071b50-b651-11e6-8057-0023442951d3.PNG)

**Comment by ivannaranjo** [comment]
I think that we can try to fix the error message but the situation cannot be fixed. The user changed the authorized network on the server side.
