### ISSUE TITLE
New Google Cloud Web API project fails to build.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#323]
![newwebapiproject](https://cloud.githubusercontent.com/assets/11778530/20776423/535dec58-b715-11e6-988c-c2f7b8fd0017.png)
![newwebapiprojectbuildfail](https://cloud.githubusercontent.com/assets/11778530/20776425/5752a07e-b715-11e6-86a0-a53f5c5a5184.png)

**Comment by ivannaranjo** [comment]
Did the nuget package succeed to be installed? Wondering if your nuget configuration is not correct.

**Comment by ivannaranjo** [comment]
Can't repro when NuGet packages are restored ahead of time.
