### ISSUE TITLE
Log Viewer,  add "Add an account" link when there is no account available.

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#328]
Currently,  it closes the Google Cloud Stackdriver Log Viewer tool window when the user resets account.
The preferable solution is to show a "Add an account" link to ask user to add an account.

**Comment by ivannaranjo** [comment]
Is this something that you can do for Q2? Should we punt?

**Comment by Deren-Liao** [comment]
Just punt it .
