### ISSUE TITLE
Calls to dotnet CLI should set the working directory

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-visualstudio#342]
dotnet determines which SDK version to use by walking up from the CWD until it finds a global.json.

It looks like this isn't happening when calling "dotnet publish", as preview4 was being used for me, instead of preview2 as specified in global.json. Renaming my preview4 directory fixed this as a workaround.

**Comment by ivannaranjo** [comment]
So the CWD should be set to the project's root?

**Comment by jskeet** [comment]
Just for the dotnet process, yes - I think that's the best approach.
