### ISSUE TITLE
Log Viewer, Error Reporting,  enable picking different project.

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#346]
When a project is not what one wants,  user is required to change the current project on Cloud Explorer window.    For new users, it is not obvious to them.    

An improvement would be to set the project name as a combo box so as for user to choose different project.

![account-project title bar](https://cloud.githubusercontent.com/assets/22829476/21556229/b664af38-cdd3-11e6-998c-cc585c4fae69.PNG)

**Comment by ivannaranjo** [comment]
This should be integrated with the Cloud Explorer though. The extension has a "current" GCP project on which all operations happen. The user should change it from the central location. We might also add a help message on where to set the current project.

If we allow different projects for different windows it will get really confusing, the deploying will happen potentially in a different window, etc, etc... Also each window should retain the project, and account, for which it was opened. The user should open a new window every time instead. Similar to how it is done in the cloud console.

But I will open a UI design bug to try to make the current project setting more visible.

**Comment by ivannaranjo** [comment]
See #351

**Comment by Deren-Liao** [comment]
At least I want to show a link that takes user to the place of changing a
project.
