### ISSUE TITLE
Add a toolbar that can be used to change the current GCP project.

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-visualstudio#351]
Currently you must open the Cloud Explorer to change the current GCP project on which the extension operates. Add a tool bar that has a combobox to change the current GCP project and that can be visible all of the time.

Also investigate if we can show the current GCP project's name in the VS title bar, status bar, etc...

**Comment by ILMTitan** [comment]
See https://github.com/github/VisualStudio/blob/12a81c6b9edf743147c98809f9ea0610c3ca7e78/src/GitHub.InlineReviews/Services/PullRequestStatusBarManager.cs for a possible way to add to the VS StatusBar.

**Comment by ILMTitan** [comment]
Also see StackOverflow question [add a button to the main window frame control pane in visual studio](https://stackoverflow.com/questions/28046127/how-to-add-a-button-to-the-main-window-frame-control-pane-in-visual-studio-2013)
