### ISSUE TITLE
Build the project with latest source before publishing project.

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#357]
The issue:
    I modified some code and I forgot to "Save"  and I do a new publish.
    Now when I open the page, I see the old web page.

The proposed fix:
    Force to save the unsaved  before publishing.
   Alternatively, prompt to developer to ask a confirmation.

**Comment by ivannaranjo** [comment]
The extension should invoke the "File.SaveAll" command before starting the publish process. Similar to what the build or F5 process does.
