### ISSUE TITLE
Use the Service Management API to enable/disable GCP APIs

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-visualstudio#358]
The [Service Management API](https://cloud.google.com/service-management/overview) is in beta, it should be possible to use the API to enable/disable the GCP APIs that an app needs from within the VS extension. See [here](https://cloud.google.com/service-management/enable-disable) on the API for this.

**Comment by ILMTitan** [comment]
This was fixed in #833.
