### ISSUE TITLE
Would like to right-click on an instance of SQL Server in the Explorer to add a Data Connection

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-visualstudio#363]
Just like we do with a CloudSQL instance. Do we have the tags we need to identify a SQL Server instance and connect to it?

**Comment by ivannaranjo** [comment]
Not sure if we have the tags for this, or if we can use the license in the hard drive for the instance. Presumably this should be an option of the GCE instance only enabled if it is a SQL Server.
