### ISSUE TITLE
Show app engine instance id in the explorer

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#371]
I am using the version merged from q1_master.  If you believe I am using a wrong version, just close it.

As shown in the following picture, the  app engine instance  does not show any label.  If this is not a bug, I'd ask you to consider to add instance id to it.

![gae_instance_no_label](https://cloud.githubusercontent.com/assets/22829476/22171342/3bf37986-df40-11e6-9102-6d4c8232ed6e.PNG)

**Comment by ivannaranjo** [comment]
This is referring to the name of the GCE instance that runs the backend for the app. Yes, this is a bug, the instance name should be shown correctly.
