### ISSUE TITLE
App Engine Asp.net Core, deploy multiple services.

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#372]
Currently, I don't see a choice to select service name other than "default". 
I was trying to deploy different project and didn't find options. 

I built the extension locally with code synced from q1_master.  Please just close it if this is a non-issue.

**Comment by ivannaranjo** [comment]
This is working as intended, the service name is specified in the app.yam. If you create one in the root of your project we will take it and use it instead.
