### ISSUE TITLE
Can't add an account with an existing password via Manage Windows Credentials

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-visualstudio#381]
This is what happens when I try:
![image](https://cloud.githubusercontent.com/assets/2568253/22350310/20aad692-e3c8-11e6-898b-34256dc4c9fa.png)

If I try again after this, I get VS crashing.

**Comment by ivannaranjo** [comment]
Ah, the ':' in the project name is causing trouble. This will affect users using the organization. Will fix right away.

**Comment by ivannaranjo** [comment]
There's a fix for this in review.
