### ISSUE TITLE
Error message for a failure to set a pw is long and confusing

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-visualstudio#397]
Can we format this message better? Perhaps provide a summary and details? And a scrollbar?

![vs-error-msg-long](https://cloud.githubusercontent.com/assets/2568253/22635160/dc82d642-ebe5-11e6-9a0a-63d6701fc1d0.png)

**Comment by ivannaranjo** [comment]
Will substitute the message for a built-in message with probable causes that is more readable.
