### ISSUE TITLE
Deploy other well known .yaml files, cron.yaml, index.yaml, etc...

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-visualstudio#403]
Detect them in the project root and offer up a checkbox for the user to deploy them together with the app.

**Comment by SurferJeffAtGoogle** [comment]
There are potentially many files, and their purpose will be unclear to new users who see them in project explorer.  So I suggest that we put *.yaml and Dockerfile in an /appengine subdirectory with a README.

**Comment by ILMTitan** [comment]
The Cloud SDK recognizes 5 "config" yamls. cron, dispatch, dos, index, and queue. Everything else is a "service" yaml e.g. app.yaml.

**Comment by SurferJeffAtGoogle** [comment]
Ok.  I'll write the samples with the Dockerfile and *.yaml in the project root.

**Comment by ivannaranjo** [comment]
Only the service yamls (as Jim says) are associated with the code, which is why that's the one that has always been deployed. I think that if we add an option to deploy these files we need to do it in a separated way. Probably a separated dialog that allows the user to select what "other" .yaml files to deploy.

**Comment by SurferJeffAtGoogle** [comment]
Sounds good.  In terms of UI, maybe I can right-click on a .yaml file and
choose "Publish to App Engine..."?

**Comment by ivannaranjo** [comment]
And to be honest the cron.yaml, index.yaml etc do not need to be at the root because they don't deploy code, they are really just configuration. They could be in a separate directory with a README as suggested. The only one that needs to be at the root is app.yaml since it delivers code.
