### ISSUE TITLE
Container engine deployment UI surprise

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-visualstudio#417]
When deploying a backend to Container Engine, I unticked "Expose the service to the public internet" because it's a backend... the checkbox below ("Open website after publish process finishes") is disabled, but is still checked.

Perhaps this should actually be a radio-button with "public" and "non-public" and make the "open website" only part of the "public" part?

**Comment by ivannaranjo** [comment]
This is now (hopefully) fixed by #447
