### ISSUE TITLE
When opening a project without solution the Tools > Google Cloud Tools > Publish... menu item is disabled.

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-visualstudio#421]
When opening an ASP.NET Core project that doesn't have a solution the "Publish..." menu item under the Google Cloud Tools menu is disabled. This seems to happen because there's no solution for this project at the time the project is loaded.

**Comment by ivannaranjo** [comment]
As a workaround the context menu for the project does work.

**Comment by danghung1202** [comment]
Hi @ivannaranjo Currently, I have same issue as you mentioned, could you show me the workaround for that?

**Comment by ivannaranjo** [comment]
If you right click on the project in the solution explorer you will see the "Publish to Google Cloud..." menu option there.

**Comment by ILMTitan** [comment]
This was already fixed.
