### ISSUE TITLE
Allow user to choose build configuration (Release/Debug) to Publish

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#431]
Currently Google Cloud Visual Studio Extension only publishes release build.   
If the current project active configuration is Debug.  I would hope the it pushes debug version for me too.

**Comment by ivannaranjo** [comment]
This will only be useful once we have a debugger option.

**Comment by Deren-Liao** [comment]
What do you mean debugger option?
I was trying to publish debug build. With debug build, Stackdriver logging, Error Reporting can obtain the source information. In release build, it won't.   
It's going to be useful if user wants to debug the application with either error reporting or logging.

**Comment by ivannaranjo** [comment]
That's the point, the cloud debugger work will eventually make this not needed. That's how the app should be debugged. Until then releasing a debug build to production is not going to change much. I think that we need to find out why we can't get the line numbers on release builds.

**Comment by ivannaranjo** [comment]
General problem though, we only publish the "Release" configuration. We should allow the user to choose what configuration to publish, default to the currently selected one.

**Comment by iantalarico** [comment]
Dropping to P3 for the Stackdriver bits to work it's a matter of making sure you deploy your PDBs with your application which will still work with a release build
