### ISSUE TITLE
./tools/ensure_no_unused_strings.sh detection false negative 

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#457]
When I used syntax of 
using static GoogleCloudExtension.Resources;
It says some strings defined in resources are not used.

**Comment by ivannaranjo** [comment]
This is not a bug. This is by design actually, we want to be explicit about the strings that we're using in our project. Using the class makes this explicit and easy to check.

**Comment by Deren-Liao** [comment]
I understand and want to follow the "rule".
