### ISSUE TITLE
Deployment to flex fails

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-visualstudio#462]
I have a machine with a fresh install of VS, the plugin, and gcloud.  When I run a publish on a flex app for the first time, it fails trying to elevate to install the `beta` component in gcloud.  

I ran as admin, tried again, and then got this:
You do not currently have this command group installed.  Using it 
requires the installation of components: [beta]

ERROR: Cannot use bundled Python installation to update Cloud SDK in
non-interactive mode. Please run again in interactive mode.

If you really want to run in non-interactive mode, please run the
following command before re-running this one:

```
  FOR /F "delims=" %i in ( '""C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd"" components copy-bundled-python'
  ) DO (
    SET CLOUDSDK_PYTHON=%i
  )

(Substitute `%%i` for `%i` if in a .bat script.)
Installing component in a new window.

Please re-run this command when installation is complete.
    $ C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\lib\gcloud.py beta app deploy C:\Users\beckwith\AppData\Local\Temp\3tbbp3zq.vwr\app.yaml --version=20170228t012549 --promote --skip-staging --quiet --project=dotnet-next --credential-file-override=C:\Users\beckwith\AppData\Local\googlecloudvsextension\accounts\2e0cd67b69f98b14fb2cd043ec523fcefcfd9b2f.json
Failed to deploy project hellogcp to App Engine Flex.
```

To get around it, I had to run PS in an elevated window, `gcloud components install beta`, and then everything worked.

**Comment by JustinBeckwith** [comment]
If you're interested... here's how I worked around this problem with my App Engine UI thingy:
https://github.com/JustinBeckwith/trebuchet/tree/master/extras/uac

It uses a binary generated [here](http://code.kliu.org/misc/elevate/) that does elevation for spawned processes.  We probably can't directly use that, but it should point y'all in the right direction :)

**Comment by ivannaranjo** [comment]
Ah, is not supposed to to try to install the beta component, just notify that the component is missing and has to be installed. This is a bug because the App Engine Flex deployment code is not checking for the presence of the beta component before the deployment starts.
