### ISSUE TITLE
Web.config needs links to pages explaining variables

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#478]
I created a new GoogleAspNetMvc application, look in web.config, and see this:
```xml
    <!-- [START google_error_reporting_config] -->
    <add key="google_error_reporting:serviceName" value="NAME-OF-YOUR-SERVICE" />
    <add key="google_error_reporting:version" value="VERSION-OF-YOUR-SERVICE" />
    <!-- [END google_error_reporting_config] -->
```
I don't know how to get values to insert here.  Can you show me a link?

**Comment by ILMTitan** [comment]
I have added default values to the project templates in #607.
I am also adding comments with links to https://cloud.google.com/error-reporting/docs/formatting-error-messages. Easy enough to do for the .NET Framework XML configs. I was considering also adding comments to the appsettngs.json in the .NET Core templates. JSON does not have a comment syntax, but I could just add new elements named "$comment" that will not be used for anything.
