### ISSUE TITLE
Exception when I run new GoogleAspNetMvc project

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#479]
```
+		$exception	{"The logging and error reporting libraries need a project ID. Update Web.config and add a <projectId> entry in the <log4net> section."}	System.Exception
```

The text of this exception is really useful, and I'll be able to figure out how to fix it.  But I'll get instant gratification if you can prepopulate these values for me.  Why not grab the value from `gcloud config get-value project` and populate web.xml for me?

**Comment by ILMTitan** [comment]
PR #607 gives a default value to the project template.
