### ISSUE TITLE
Publish dialog doesn't remember the VM I most recently published to.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#480]
2 minutes ago, I published to an instance called hello-aspnet.  But when I publish again the dialog has forgotten my choices:
![image](https://cloud.githubusercontent.com/assets/11778530/23484092/5c479a0a-fe8a-11e6-8cd1-a8f95e6b1a76.png)

**Comment by ILMTitan** [comment]
Sub-issue of #863

**Comment by ILMTitan** [comment]
Now being tracked as part of #863.
