### ISSUE TITLE
Build under 2017 fails

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#503]
This is not a bug.  
This is a feature request to support VS 2017.

The "GetDeploymentPathFromVsixManifest" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Settings.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Settings.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.VsSDK.Build.Tasks.GetDeploymentPathFromVsixManifest.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].	GoogleCloudExtension

**Comment by Deren-Liao** [comment]
Looks it is a Visual Studio 2017 bug. 
https://developercommunity.visualstudio.com/content/problem/4493/build-of-vsix-project-fails-with-msb4018-the-getde.html
Solution is 
"Just ran into this also. Project properties, and on VSIX tab, uncheck "Deploy VSIX content to experimental instance for debugging." It at least lets me build, without debug capability I think."

**Comment by Deren-Liao** [comment]
It's VS 2017 bug. 
By the time if

**Comment by osnjunior91** [comment]
I was having this error, after updating the dependencies of the project via Nuget, the error disappeared.
