### ISSUE TITLE
Cloud Explorer Error Text Relocation

### ISSUE THREAD

**Issue by ahandley** [GoogleCloudPlatform/google-cloud-visualstudio#504]
![screenshot1](https://cloud.githubusercontent.com/assets/25370919/23911186/41cad304-0899-11e7-93b2-d696be342e00.png)
![screenshot2](https://cloud.githubusercontent.com/assets/25370919/23911187/41e1e666-0899-11e7-963b-67f2749263ca.png)

As you can see from the screenshots, the error text needs to be relocated from the window header to the actual window itself.  It took me a while to be able to see my error, and that was only after I figured out to maximize the window.

Steps to reproduce:
Follow the guide: https://cloud.google.com/tools/visual-studio/docs/quickstart
In section "Deploy an ASP.NET app" step 4.  
If you try this when the virtual machine is off, it throws the error shown above.

**Comment by ivannaranjo** [comment]
The message is showing up in the title instead of on the message textbloc for the dialog
