### ISSUE TITLE
Inconsistent Docs in the Quickstart

### ISSUE THREAD

**Issue by ahandley** [GoogleCloudPlatform/google-cloud-visualstudio#505]
![screenshot4](https://cloud.githubusercontent.com/assets/25370919/23911607/93634a60-089a-11e7-9686-bfc4ca57a52a.png)

In the [quickstart](https://cloud.google.com/tools/visual-studio/docs/quickstart), there is inconsistent documentation as shown in the screenshot.

**Comment by ivannaranjo** [comment]
This now fixed.
