### ISSUE TITLE
Improve Error Messages for Stopped VM's

### ISSUE THREAD

**Issue by ahandley** [GoogleCloudPlatform/google-cloud-visualstudio#506]
I received an error from the Google Cloud Explorer that was very vague (talking about variables that are hidden to the user)

Steps to reproduce:
Follow the guide: https://cloud.google.com/tools/visual-studio/docs/quickstart
In section "Deploy an ASP.NET app" go to step 4.
Stop the virtual machine, and continue the guide.
It throws the error shown below:

![screenshot1](https://cloud.githubusercontent.com/assets/25370919/23911935/867f7d7c-089b-11e7-962d-8ff76dc11e52.png)

This is related to bug #504

**Comment by ivannaranjo** [comment]
The extension should check the running status of the VM, and definitely fix the error message. As a principle we should never show messages coming from exceptions to the user, they are not very useful for them.

**Comment by Deren-Liao** [comment]
Fixed
