### ISSUE TITLE
Add "Google Cloud API manager" 

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#509]
It can contain the full list of supported Google Cloud APIs

- Add/Remove nuget packages of the APIs

- Insert necessary initialization code, especially for authentication etc
Example:  Log4Net,   adding the config, reading config etc code.
                Error Reporting Diagnostics,   adding the code easily...  

- Links to documentation, samples

**Comment by ivannaranjo** [comment]
This is done today in the templates. The apps are created fully supporting logging, error reporting and with the right nuget packages added to them.

As for adding new APIs, and possibly examples, etc... we should track this in #358, since this will also involve enabling APIs.

**Comment by ivannaranjo** [comment]
This is not full duplicate however, I think that this is more of full fledge API manager feature.
