### ISSUE TITLE
Properly dispose Timer at AutoReloadButton

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#514]
google-cloud-visualstudio/GoogleCloudExtension/GoogleCloudExtension/Controls/AutoReloadButton.cs
A dispatch timer is created when an autoreload button instance is created.
When the button is disposed, the timer object is not guaranteed to be disposed by GC.  
There should be appropriate way for WPF custom control to dispose resources.

**Comment by ivannaranjo** [comment]
Please provide a bit more of context to see how this bug can be triaged.

**Comment by Deren-Liao** [comment]
Seems somebody suggested a solution at http://stackoverflow.com/questions/20073750/custom-control-and-dispose.  I'll try it out later.

**Comment by Deren-Liao** [comment]
The Dispatcher timer is not disposable. But I can stop it by setting the binded Command null.
