### ISSUE TITLE
Custom GCE VM instances not showing up

### ISSUE THREAD

**Issue by benwulfe** [GoogleCloudPlatform/google-cloud-visualstudio#515]
I have a custom GCE VM instance and it doesnt show up in the VS cloud explorer:

SShot:
https://screenshot.googleplex.com/i0TngM6kH5H.png

which is created from a custom image:
https://screenshot.googleplex.com/ZxJ2g6ynSUE.png

**Comment by ivannaranjo** [comment]
Thank you for opening the bug here. We need more details on the machine that doesn't show up and possible access to the project so I can debug what is going on.

Can you post the result of "gcloud compute instances describe" on that machine?

**Comment by ivannaranjo** [comment]
I think I see what is going on, the problem is that we can't identify this custom image as a Windows image.

Please post the `gcloud compute instances describe` for that instance so we can see how the disks are configured.
