### ISSUE TITLE
Advanced filter box , limit the max lines to around 6 ~ 8 lines

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#542]
Currently, the max height can goes up to 30 lines of text. In that height, log view is hidden.

![issue-advanced-filter-height](https://cloud.githubusercontent.com/assets/22829476/24681709/44ca5b84-194b-11e7-8bb7-53c1774ec956.PNG)

**Comment by ivannaranjo** [comment]
Actually we should probably make the textbox fixed height, otherwise the UI will keep on moving when you add new lines, which can be very jarring.

**Comment by Deren-Liao** [comment]
The design based on assumption that most user only use a few lines .  Keep the box height shorter help leave more space for real log lines.   Even for the very few cases user wants to input more,  changing height does not look bad to me , as I tried .
