### ISSUE TITLE
UI Review feedback - move advanced filter help link to right that align the to simple filter button

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#543]
![issue-advanced-filter-helper-link-alignment](https://cloud.githubusercontent.com/assets/22829476/24681793/9e4da774-194b-11e7-9be5-657d28d7502f.PNG)

Move the link right align the "To Simple Filters" button.
And change the color to black when not highlighted.

**Comment by ivannaranjo** [comment]
Make sure to use the common hyperlink style, or update the common hyperlink style. We osuld be consistent.

**Comment by Deren-Liao** [comment]
By looking at the changed layout, I believe the current layout is better.
