### ISSUE TITLE
Add cloud-builds to list of filtered Pub/Sub topics.

### ISSUE THREAD

**Issue by ILMTitan** [GoogleCloudPlatform/google-cloud-visualstudio#556]
cloud-builds is another gcp service topic. It should not show up in the list of topics to manage.

**Comment by ivannaranjo** [comment]
Also add the `repository-changes.*` topics to the list. I wish we would have a common prefix to mark the _built-in_ topics.

**Comment by ILMTitan** [comment]
are there any `repository-changes.*` other than `repository-changes.default`?

**Comment by ivannaranjo** [comment]
Yes, there's a topic per repository created in the project.

**Comment by ivannaranjo** [comment]
Thinking on moving to Q3, is this something you can take care of this week?

**Comment by ILMTitan** [comment]
I can take care of it this week.

**Comment by ivannaranjo** [comment]
Great, thank you for taking care of it.
