### ISSUE TITLE
Deployment two referenced dlls are not included in pubish 

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#564]
I open it for myself to keep track.
This is more likely a bug of MSBuild.exe or MsDeploy.exe . 
As I created another simpler example, it did not reproduce. 
The reproducible solution includes multiple git repository projects with local project paths.  So not easy for others to set up the solution to debug.

**Comment by ivannaranjo** [comment]
Care to add more details about what failed?

**Comment by Deren-Liao** [comment]
The project reference to Log4Net, and Dev..Source.V1 project not Nuget.  The two dlls are not included when publishing. They are missing.

**Comment by ivannaranjo** [comment]
Oh, I see... That seems like a bug in the build. Publishing should collect all dependencies.

**Comment by ivannaranjo** [comment]
Is there any update on this, anything actionable for the extension?

**Comment by Deren-Liao** [comment]
I did not have chance to look into this.  I'll see if I can do some
investigation this Friday.

**Comment by Deren-Liao** [comment]
I still don't get time on this...  Mark. :(

**Comment by Deren-Liao** [comment]
Close for now
