### ISSUE TITLE
Path.Combine throws exception

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#571]
return Environment.GetEnvironmentVariable("PATH")
                .Split(';')
                .Select(x => Path.Combine(x, GitExecutable))
                .FirstOrDefault(x => File.Exists(x));

Path.Combine throws exception on path   "\"C:\\Program Files (x86)\\Notepad++\\\""

**Comment by Deren-Liao** [comment]
Later test shows "C:\Program Files (x86)\Notepad++\" is a valid safe path. It must be something else that I did not repro. Still it's safer to fix the bug.

**Comment by ivannaranjo** [comment]
What is the action item on the extension? Do you have a fix for this?

**Comment by Deren-Liao** [comment]
Fixed.
