### ISSUE TITLE
In the ASP.NET Core templates add a controller for the /_ah/* routes.

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-visualstudio#572]
The `/_ah/*` routes are special routes used by App Engine to notify the app of events, such as startup and shutdown and to probe for the health state of the app.

The App Engine health checker will probe the `/_ah/health` route periodically. All that is needed is for the app to **not** return a 5XX error code. The templates are not handling this route which means that the app returns 404s, this is not marking the app as unhealthy but it is adding entries to the error logs.

We should have a default handler for the `/_ah/*` routes that handles all of this, including some sort of callbacks for lifetime events (startup, shutdown) that the app can hook into.

**Comment by ILMTitan** [comment]
Doing this just spams different logs (specifically those from Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker).
