### ISSUE TITLE
Google Error Reporting should read ServiceName and Version from metadata.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#575]
I created a new GoogleAspNetCoreMvc application and see this in appsettings.json:
```json
  "GoogleErrorReporting": {
    "ServiceName": "NAME-OF-YOUR-SERVICE",
    "Version": "VERSION-OF-YOUR-SERVICE"
  }
```

I want an IConfigurationProvider that inspects the metadata and provides these values from:
```
Key   : gae_backend_name
Value : default

Key   : gae_backend_version
Value : 20170418t085104
```

**Comment by ILMTitan** [comment]
Do you really want a full `IConfigurationProvider`, or do you just want a method similar to `GetProjectId()`?

**Comment by SurferJeffAtGoogle** [comment]
Actually, I think the most idiomatic way would look something like this:

```
            services.AddGoogleExceptionLogging(options =>
                options.LoadFromGoogleMetadata() || options.LoadFromConfiguration(Configuration));

```

**Comment by ILMTitan** [comment]
It looks like you are right, but that Google.Cloud.Diagnostics.AspNetCore does not support that method.
