### ISSUE TITLE
Templates should avoid spamming logs.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#576]
When an application is deployed to app engine, app engine checks /_ah/health multiple times per second.  The result is that the logs are so flooded with /_ah/health requests that it's a PITA to find any useful information in the logs.  Let's stop that.

One solution:
Provide appsettings.Staging.json and appsettings.Production.json with logging flags set to something less verbose like:
```json
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Information",
      "System": "Warning",
      "Microsoft": "Warning"
    }
  },
```

**Comment by SurferJeffAtGoogle** [comment]
/_ah/health requests also flood traces.

**Comment by iantalarico** [comment]
We fixed the trace issue in the client library (https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/847).  We should be doing a new release this week and will just need to update the versions in the templates.

**Comment by ivannaranjo** [comment]
Seems like the spam in the logs happens regardless of whether we handle the request or not. Us handling the `/_ah/health` route doesn't change the logging behavior, it just changes the HTTP error code from 404 to 200.
