### ISSUE TITLE
HandleExceptions should not should not call ErrorHandler.IsCriticalException(ex) and throw.

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#589]
* googlecloudextension\utils\errorhandlerutils.cs  .
!IsCriticalException(ex) already filters out non critical exception, 
 if (ErrorHandler.IsCriticalException(ex)) looks redundant.

* Should we expose exception to user by doing UserPromptUtils.ExceptionPrompt(ex);

 ```
public static void HandleExceptions(Action action)
{
    try
    {
        action();
    }
    catch (Exception ex) when (!IsCriticalException(ex))
    {
        Debug.WriteLine($"Uncaught exception: {ex.Message}");
        if (ErrorHandler.IsCriticalException(ex))
        {
            throw;
        }
        EventsReporterWrapper.ReportEvent(UnhandledExceptionEvent.Create(ex));
        UserPromptUtils.ExceptionPrompt(ex);
    }
}
```

**Comment by ivannaranjo** [comment]
We should not be exposing the error message from the exception to the user at all. We should have a generic error message for these _unknown_ errors.

**Comment by ivannaranjo** [comment]
I'm taking it and producing a small fix.
