### ISSUE TITLE
When Web application is in a solution folder Then Google Cloud tools context menu item is disabled

### ISSUE THREAD

**Issue by suprmorten** [GoogleCloudPlatform/google-cloud-visualstudio#593]
If you put your web application inside a solution folder it always shows up as disabled. Changing target framework does not affect it.

![image](https://cloud.githubusercontent.com/assets/1232034/25554422/8598eab4-2ccd-11e7-83a8-57f4e35f3ddc.png)

**Comment by ivannaranjo** [comment]
Investigating to see if we can do something before M2 release.

**Comment by ivannaranjo** [comment]
Turns out the extension is receiving a `SolutionFolder` instead of a project, we need to enumerate deep into the solution folders to find all of the projects.
