### ISSUE TITLE
Not possible to Publish Asp.Net using Google Tools - Web.config transformation

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#619]
Say I have Web.QA.config transformation and I select the QA configuration. When publishing using visual studio to some local folder or an IIS it works as expected. But when using the Google cloud extension and publish to the Google environment it always publish without transformation, meaning with the web.config configuration.

As described here:
http://stackoverflow.com/questions/43993490/publish-asp-net-using-google-tools-web-config-transformation

**Comment by ivannaranjo** [comment]
We have a hardcoded configuration sadly, need to fix this.
