### ISSUE TITLE
Add Remote debugger target windows of x86 CPU support

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#624]

**Comment by ivannaranjo** [comment]
What do you mean by this bug?

**Comment by Deren-Liao** [comment]
Currently, I assume all Debuggee VM are x86 windows server.  So I copy x64 version of debugger remote tools.   As I checked,  GCE does not provide x86 windows server now.  I wonder if I should add x86 support.

**Comment by ivannaranjo** [comment]
Moving to M3. I think that we should only support what GCE supports.

**Comment by Deren-Liao** [comment]
Confirmed with GCE team there won't be x86 (32 bit) Windows image added.
