### ISSUE TITLE
Add template support for .NET Core 1.1

### ISSUE THREAD

**Issue by ILMTitan** [GoogleCloudPlatform/google-cloud-visualstudio#635]
Ivan is working on getting CloudBuilder support for .NET Core 1.1. The templates should be updated to also support that.

**Comment by ivannaranjo** [comment]
The extension support for 1.1 is being tracked on #646

**Comment by ivannaranjo** [comment]
Thinking about moving this to early Q3, do you think you can get to this in the next week?

**Comment by ILMTitan** [comment]
I do not. I am have not investigated what is required.

**Comment by ivannaranjo** [comment]
Moving to Q3.

**Comment by ILMTitan** [comment]
In VS 2017, changing the framework to .NET Core 1.1 is a simple matter of going to project properties and selecting 1.1 from a dropdown. When creating the project I can update the framework to the latest version, but I am not sure that is worth anything. Code for this change is available at [ILMTitan/set-template-framework-latest](https://github.com/ILMTitan/google-cloud-visualstudio/tree/set-template-framework-latest)

I also could add a pop-up to ask which framework version to use, but I don't think that provides any benefit above the project properties.

**Comment by ILMTitan** [comment]
I am going to enable the code to set the framework to the latest version. Reopening to track that.

**Comment by ILMTitan** [comment]
Fixed in PR #792.
