### ISSUE TITLE
Unable to build ASP.NET MVC 4 project template

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-visualstudio#639]
I'm not sure what the issue is here. I assume we just have a bad project template?

## Repro

- Fresh install of the latest Cloud Tools for Visual Studio extension (v1.1.11.0).
- File \ New Project...
- Templates \ Visual C# \ Google Cloud Platform \ Google ASP.NET 4 MVC
- CTRL + SHIFT + B

**Build Failure**

````
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'System.Net.Http' could not be found.	delete-GoogleAspNetMvc1			
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Net.Compilers.1.0.0\build\Microsoft.Net.Compilers.props.	delete-GoogleAspNetMvc1	C:\Users\achri\OneDrive\Documents\Visual Studio 2017\delete-GoogleAspNetMvc1\delete-GoogleAspNetMvc1.csproj	362	
Warning		The referenced component 'WebGrease' could not be found.	delete-GoogleAspNetMvc1			
Warning		The referenced component 'Owin' could not be found.	delete-GoogleAspNetMvc1			
Warning		The referenced component 'System.Xml' could not be found.	delete-GoogleAspNetMvc1			
Warning		The referenced component 'System.Web.Routing' could not be found.	delete-GoogleAspNetMvc1			
... snip ...
````

## Attempted Workarounds

(1) Removing the MSBuild-based check (which is where the error comes from in the `.csproj` file just causes compiler errors when the assemblies aren't found.

(2) Running `Update-Package` in the Package Management Console does _something_ but in the output spam there are a few errors as well. When it completes, I still get errors about missing types and assemblies such as ` Microsoft.AspNet.Identity`.

(3) I'd guess it has to do with my Visual Studio install not having the ASP.NET and/or web development tools. However, going to Help \ About in Visual Studio I see it is installed:

```
Microsoft Visual Studio Community 2017 
Version 15.2 (26430.6) Release
VisualStudio.15.Release/15.2.0+26430.6
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA736
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA736
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA736
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA736
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.6.00404.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30503.0
ASP.NET and Web Tools 2017

... snip ...
````

Note however that if I create a new project using the ASP.NET Core MVC app template, I can press F5 and everything just works. (Well, it throws at the "Please replace this with your project-ID" part.)

**Comment by chrsmith** [comment]
Also, that project template targets .NET 4.5.2. Is that expected? Or shouldn't we have it target 4.6.1?

**Comment by ivannaranjo** [comment]
Just tried it myself and the packages were restored automatically and the build succeeded. Do you have the "Allow NuGet to download missing packages" and "Automatically check for missing packages during build in Visual Studio" checkboxes checked? They are Options in the "Package Manager" tab.

These checkboxes are on by default, at least on my installation. So when I build "nuget restore" is run automatically and the missing packages downloaded.

This has come up a few times before, not sure how this setting is not on for everybody by default. I certainly didn't turn it on myself.

As for the target .NET 4.5.2, we cannot really update since the ASP.NET image doesn't have .NET 4.6.1 installed.
