### ISSUE TITLE
"Publish to Google Cloud.." button is grayed out for me.

### ISSUE THREAD

**Issue by JoshLefebvre** [GoogleCloudPlatform/google-cloud-visualstudio#640]
I'm currently usng Visual Studio 2017 (15.026228) and installed google Cloud Tools for Visual Studio (1.1.11.0) and whenever I try to publish my app to google cloud under tools the "Publish to Google Cloud" is greyed out. Whenver I right click on the project I want to publish the "Publish to Google Cloud" button does not even appear. I'm currently logged in to my account with the Google Cloud Explorer and all my instances are showing correctly. Am I missing something? 

![gcp](https://cloud.githubusercontent.com/assets/22512098/26556241/6f2dcf90-4467-11e7-989a-01386a93d92e.png)

**Comment by rbozan** [comment]
How did you fix this
