### ISSUE TITLE
Unclear how to deploy to GAE flex outside of Visual Studio

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-visualstudio#659]
I have an existing GAE flex application. How do I deploy it without using Visual Studio?

`gcloud app deploy ./app.yaml` and `dotnet publish && cp ./app.yaml <publishdir> && gcloud app deploy <publishdir>/app.yaml` both fail with the same error:

````
ERROR: (gcloud.app.deploy) Your application does not satisfy all of the requirements for a runtime of type [aspnetcore].  Please correct the errors and try again.
````

Is this a supported scenario? If so, what are the requirements of the `aspnetcore` runtime?

**Comment by RyanThomas73** [comment]
I've seen the same problem, you'll need to run the beta track command for flex.
`gcloud beta app deploy ...`

**Comment by ivannaranjo** [comment]
Indeed, you need to use `gcloud beta app deploy`, see the quick start at https://cloud.google.com/endpoints/docs/get-started-app-engine-dotnet.

**Comment by ivannaranjo** [comment]
Yep, you need to use the `gcloud beta app deploy...` trench, since the runtime builders are still in beta. The [App Engine Flex .NET quickstart](https://cloud.google.com/appengine/docs/flexible/dotnet/quickstart) has instructions on how to deploy the app using Visual Studio and the command line.
