### ISSUE TITLE
ERROR: (gcloud.beta.app.deploy) Could not find Cloud Build config

### ISSUE THREAD

**Issue by hokumski** [GoogleCloudPlatform/google-cloud-visualstudio#692]
Deployment to App Engine Flex fails with error:

Beginning deployment of service [default]...
Building and pushing image for service [default]
ERROR: (gcloud.beta.app.deploy) Could not find Cloud Build config [gs://runtime-builders/aspnetcore-efault-builder-20170609084336.yaml]. Please ensure that your app/runtime_builders_root property is set correctly and that [efault-builder-20170609084336] is a valid version of the builder for runtime [aspnetcore].
Failed to deploy project PROJECTNAME to App Engine Flex.

**"efault"**? Is ut typo somewhere? But where? 
Misconfiguration on GCloud side?

**Comment by hokumski** [comment]
gcloud components update

**Comment by csells** [comment]
@hokumski has this problem been fixed to your satisfaction?

**Comment by hokumski** [comment]
@csells yes

**Comment by csells** [comment]
Thank you. Can I also ask whether you're using the Google .NET Runtime (which you get automatically via gcloud app deploy) or whether you're using a Custom Dockerfile, e.g. using Microsoft's .NET Runtime.

**Comment by hokumski** [comment]
@csells I used Google .NET Runtime
