### ISSUE TITLE
The template wizard pick project dialog should not simply hide elements.

### ISSUE THREAD

**Issue by ILMTitan** [GoogleCloudPlatform/google-cloud-visualstudio#713]
The template wizard pick project dialog currently uses visibility to select the visible element of the central pane. It should instead use data templates and triggers as described in [this blog post](https://rachel53461.wordpress.com/2011/05/28/switching-between-viewsusercontrols-using-mvvm/).

**Comment by ivannaranjo** [comment]
Is this something that can be moved to Q3?
