### ISSUE TITLE
Cannot publish new empty web application.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#733]
Version 1.1.11.0

I created a new, empty, .NET core web application.  The 'Publish' and 'Create app.yaml and Dockerfile' menu items are disabled.

![image](https://user-images.githubusercontent.com/11778530/27453909-d849b118-574c-11e7-8205-d7c0099c080e.png)

**Comment by ivannaranjo** [comment]
This is now fixed in master. We had a small issue with nested solution directories. The fact that this was not reported before shows the little use that project.json is having.
