### ISSUE TITLE
Cannot create ASP.NET Core projects using Google templates in VS 2017

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-visualstudio#736]
When attempting to create new ASP.NET Core projects in VS 2017 using the Google templates the process fails with the following error message:
```
---------------------------
Microsoft Visual Studio
---------------------------
Operation could not be completed. The project file 'c:\users\ivann\documents\visual studio 2017\Projects\GoogleAspNetCoreMvc1\GoogleAspNetCoreMvc1\GoogleAspNetCoreMvc1.xproj' cannot be migrated. See the migration report for details.
---------------------------
OK   
---------------------------
```

The error message cites a migration report but this migration report cannot be, possibly because the template expansion never finished.

I have not seen this issue before as the template expansion was working correctly before.

My version of VS is 15.2 (26430.4) and verified it reproes as well with (26430.12).

This bug is a shipblocker.

**Comment by ivannaranjo** [comment]
Attempting to expand the template on VS 2015 yields this error:
---------------------------
Microsoft Visual Studio
---------------------------
The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  c:\users\ivann\documents\visual studio 2015\Projects\TestProjectMvc\TestProjectMvc\TestProjectMvc.xproj
---------------------------
OK   
---------------------------

**Comment by ivannaranjo** [comment]
Seems to only fail on Windows Server 2016, and possibly Windows 10.

**Comment by ILMTitan** [comment]
Does the versions of VS 2015 it is failing on have Microsoft .NET Core Tools? That is required for the .NET Core projects.

**Comment by ILMTitan** [comment]
I just ran VS 2017 as a debug process under VS 2015, and the template worked. I simultaneously ran a VS 2017 as a standalone process and the templates failed.

**Comment by ILMTitan** [comment]
It looks like this fails if Visual Studio 2017 is not run as an administrator.

**Comment by ivannaranjo** [comment]
I have .NET Core tools installed in all versions of VS, so I can test the templates, deployments etc... Any idea why the .props file would not be found?

**Comment by ILMTitan** [comment]
The only reason I can think of is if the *.props* file is not there.
I have not changed the *.xproj* files at all. Looking at them, they seem to be doing the correct things (using variables to find the files).

```
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">14.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>
  <Import Project="$(VSToolsPath)\DotNet\Microsoft.DotNet.Props" Condition="'$(VSToolsPath)' != ''" />
```

The only thing that could be going slightly wrong there is setting the VisualStudioVersion to 14.0 (aka VS 2015) when it is not provided.

Does that *.props* file exist? Does it exist on the wrong VSToolsPath (13.0 or 15.0)? Do the standard .NET Core templates work on the problematic VS 2015 instances? Which *Microsoft.DotNet.Props* file do they reference?
