### ISSUE TITLE
Open page with release notes on each extension update.

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-visualstudio#737]
On first launch after an update we should show a webpage, with the release notes for the update. That way we can inform the user of the new features, UI, etc... With pointers to the new documentation.

**Comment by ILMTitan** [comment]
Opening a webpage without the user asking does not seem like a good idea. 
The goal of this feature should be part of our Marketplace page, for which there is already a link when an update is available.
