### ISSUE TITLE
The ASP.NET Core global.json file specifies a version of the runtime that doesn't match the .NET Core tools for VS.

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-visualstudio#762]
VS 2015, with the VS .NET Core tools complains that the right version of the SDK is not installed. We should use the same version of the 1.0 SDK for them. Probably we should also filter that out when generating 1.1 projects as to not use a very old SDK version.

**Comment by ILMTitan** [comment]
I am not sure what you mean by this. Which version of .NET Core SDK is it requesting? Every time I try to update the global.json to version 1.0.1 or greater, the VS 2015 .NET Core Tools complains about a missing dotnet-projectmodel-server; the corresponding dll is missing from those versions as well. The last .NET Core SDK that seems to work is 1.0.0-preview2-003156.

**Comment by ILMTitan** [comment]
Apparently the .NET Core tools Preview 2 for Visual Studio 2015 comes with .NET Core SDK version 1.0.0-preview2-003131. I will change to that.
