### ISSUE TITLE
Support for OS X

### ISSUE THREAD

**Issue by hutchk** [GoogleCloudPlatform/google-cloud-visualstudio#764]
I have Visual Studio Community for Mac. The extension documentation doesn't make it clear if this OS and IDE are supported.

I tried to install the .vsix extension from the Gallery and it was not found:

<img width="820" alt="screen shot 2017-07-25 at 12 00 15 am" src="https://user-images.githubusercontent.com/26954617/28542139-4f220a72-70cc-11e7-9677-b0fa82f72384.png">

When I click on "Install from file..." and provide the .vsix file, the dialog silently goes away but the extension doesn't appear in the list of my installed extensions.

**Comment by ivannaranjo** [comment]
Visual Studio for OS X is not really Visual Studio, it is Xamarin Studio rebranded. As such we are not targeting it at this point in time. Thank you for your feedback, we will keep in mind when planning new directions for the GCP tools for .NET.
