### ISSUE TITLE
Deploy on new gcp project requires apis to be enabled

### ISSUE THREAD

**Issue by benwulfe** [GoogleCloudPlatform/google-cloud-visualstudio#783]
REPRO:

1. Create a brand new GCP project.
2. Enable billing
3. Install Cloud Tools for Visual Studio
4. Create a new Web API project
5. Deploy to Google cloud

RESULT:
detail: '[ORIGINAL ERROR] generic::permission_denied: Service ''cloudbuild.googleapis.com''
is not enabled for consumer ''project_number:475475618780''.'

I went to the interweb to investigate and decided to enable a bunch of APIs (including cloudbuild). Subsequently, the deploy succeeded.

At the very least, the error should be caught and a more explicit message about enabling the api (hopefully with a link) could be generated.

**Comment by ivannaranjo** [comment]
This requires a bit more of investigation, gcloud is meant to the enabling for the APIs for us. Perhaps is part of creating an App Engine app.
