### ISSUE TITLE
Error message when failed to create git repo is not useful and frustrating.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#786]
I see the error message, and I have no idea what to do.  `The caller does not have permission.`

Who is the caller (what is my auth identity)?  What are they trying to do?  Why don't they have permission?  How do I give them permission?  How do I change my identity?  How do I see which identities have permission?

At least some of these questions should be answered by the error message and include links or buttons to fix it.

![image](https://user-images.githubusercontent.com/11778530/29634618-45718ecc-87ff-11e7-9277-5be6140233b7.png)

**Comment by SurferJeffAtGoogle** [comment]
I tried updating gcloud, and it didn't help:
```
PS C:\Users\Jeffrey Rennie> gcloud info
Google Cloud SDK [168.0.0]
```

**Comment by SurferJeffAtGoogle** [comment]
The root cause:
```
PS C:\Users\Jeffrey Rennie> gcloud source repos create twelve-factor-demo
sourcerepo.googleapis.com is required for repository creation and is
not enabled.

Would you like to enable it? (Y/n)?  Y

Waiting for async operation operations/projectSettings.8b95c844-d72f-4567-a960-18b0ff8f2cc8 to complete...
Operation finished successfully. The following command can describe the Operation details:
 gcloud service-management operations describe operations/projectSettings.8b95c844-d72f-4567-a960-18b0ff8f2cc8
Created [twelve-factor-demo].
You may be billed for this repository. See https://cloud.google.com/source-repositories/docs/pricing for details.
PS C:\Users\Jeffrey Rennie>
```

**Comment by ivannaranjo** [comment]
This is a general problem that we have, we need to ensure that all of the necessary APIs are always enabled, or ask the user to allow use to enable them. Just as the cloud console and gcloud do.

**Comment by Deren-Liao** [comment]
Hi Ivan,
What's your thought on this?   Do we collect all the APIs we need and enable them (or make sure they are enabled) in central place ?

**Comment by Deren-Liao** [comment]
Update. We should use ServiceManagement APIs to query if an API is enabled then call Enable API to enable it if user agrees.  
The API to query the status of Enabled/Disabled is not released yet. ServiceManagement team is working to  make it public.

**Comment by Deren-Liao** [comment]
Fixed
