### ISSUE TITLE
Please fill the local path automatically with something sensible.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#787]
![image](https://user-images.githubusercontent.com/11778530/29639427-970022de-880f-11e7-8ff4-5c708ffff3e8.png)

**Comment by ivannaranjo** [comment]
Can you take a look at this issue? Does this make sense to fix?

**Comment by ILMTitan** [comment]
This should probably be initialized to `string initialLocalPath = Path.Join(DTE.Properties("Environment", "ProjectsAndSolution")["ProjectsLocation"].Value, repositoryName);`

**Comment by Deren-Liao** [comment]
This is to set git root path.  As I looked at other git plug in,  the best would be to use previous git root location.  Or  use a default git root .

**Comment by ILMTitan** [comment]
It is the git root path, but it is also most likely a Visual Studio Solution or Project folder. Therefore, we should default to a new folder under the location specified under Tools > Options > Projects and Solutions > Locations > Projects location, which is the default location when creating a new project from a template as well. The above code gets that option value.

**Comment by Deren-Liao** [comment]
Normally, people sync git code to different folder other than VS solution default folder. At least that's my case. I'll default it to %userprofile%\csr  folder.
