### ISSUE TITLE
Skip button text is cut off

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#789]
See screenshot

![image](https://user-images.githubusercontent.com/11778530/29730820-c74b796a-8996-11e7-97b3-508b43776763.png)

**Comment by ivannaranjo** [comment]
I see, the "p" is cut off.

**Comment by ILMTitan** [comment]
I am getting rid of the skip button while updating the templates with the new chooser dialog. This issue will become obsolete.

**Comment by ILMTitan** [comment]
Made obsolete by PR #792.
