### ISSUE TITLE
Publish to appengine flex does not show the name of the target project.

### ISSUE THREAD

**Issue by mkrso** [GoogleCloudPlatform/google-cloud-visualstudio#791]
Created a new Google ASP.Net Core Web API project.
Selected my account and my test project (note that first project in the list is a production project).
Ensured that selected project ID also appears in "Enter project ID".
Ensured that appsettings.json contains the correct project ID
Right click project in solution explorer -> Publish to Google Cloud...
Select Appengine Flex
Leave settings unchanged, click Publish

Project compiles successfully

Observe Output window, notice that wrong target project is used.

descriptor:      [C:\Users\xxx\AppData\Local\Temp\c1uamfsa.zjr\app.yaml]
source:          [C:\Users\xxx\AppData\Local\Temp\c1uamfsa.zjr]
target project:  [REDACTED - WRONG project]
target service:  [default]
target version:  [20170904t184514]

Publish fails because I don't have write access to the production project.

**Comment by ivannaranjo** [comment]
We should ensure that if the user selects a project for the template, that project is used for deployment and is set as the current project.

The problem that we're seeing is a disconnect between the project used when generating the template and during the session in Visual Studio. The project selected in the template dialog does not necessarily have to correspond with the project used to deploy. This is clearly causing confusion.

**Comment by ILMTitan** [comment]
Changing the template project picking dialog to also change the current Visual Studio GCP project sounds like a good thing to do, but I don't think it fully solves this problem. I think we also need to increase the visibility of the target GCP project in the publish dialog.
