### ISSUE TITLE
Error message for missing gcloud confuses users.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#793]
See https://stackoverflow.com/questions/46040439/adding-windows-credentials-on-google-cloud-platform-visual-studio

The user didn't know what to do.

The error message should provide clear instructions; something to the effect:
Please download and install gcloud by visiting [cloud.google.com/sdk](http://cloud.google.com/sdk).  (Clickable link.)

**Comment by ivannaranjo** [comment]
Interestingly enough that's what we should do already, I'll take a look. The extension should be checking that gcloud (and any necessary component) is installed before trying to change the password. This could be an old build of the extension that still required the beta component installed.
