### ISSUE TITLE
Need to add a dropdown to filter the projects per organization.

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-visualstudio#797]
Currently we show all of the accessible projects for the current user in a flat list. We need to add a way for the user to select what organization (or none) they are interested in before listing all projects.

**Comment by ILMTitan** [comment]
This seems like problem mostly faced by googlers.

**Comment by iantalarico** [comment]
@ILMTitan I vote we just close this and look into it again if we get requests from other users.  I think the new project selection UI will solve this for most.
