### ISSUE TITLE
Logviewer text is not visible on dark theme.

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-visualstudio#809]
Expected behaviour

text to adopt the theme and shown as whitish

Actual behaviour

![image](https://user-images.githubusercontent.com/9807532/31012107-870abfcc-a508-11e7-9cbf-57ddcd6df6b6.png)

Extension Info

Google Cloud Tools for Visual Studio v1.2.8.0

Visual Studio Info

Microsoft Visual Studio Enterprise 2017 Version 15.3.5
VisualStudio.15.Release/15.3.5+26730.16

**Comment by ivannaranjo** [comment]
Can you take a look?

**Comment by Deren-Liao** [comment]
Yes, I'll take a look.

**Comment by amanda-tarafa** [comment]
Actually, all the links I've seen so far on the Explorer are the same, can't be seen on the dark theme

**Comment by amanda-tarafa** [comment]
The problem with this bug, is that we are defining our own theme for the whole extension and we should respect the theme the user has chosen which can be one of the known predetermined themes or a custom one. We could mimic the predetermined ones but there's no way we can know for custom themes whether they are light or dark themes or even if they can be categorized as such.
And really, we should just respect whatever them the user has on their VS. We probably don't need any theming, or just minimum theming for very specific elements.
I already tested getting rid of the black color for text that alone fixes the first report on this thread, text is now light on the dark theme and dark on the light and blue themes, automatically.
I think we need to get rid of our own styles for the most part. Can someone validate or give more info and background as to why we have our own theming? @iantalarico @ILMTitan .

**Comment by iantalarico** [comment]
@amanda-tarafa 

I agree we should always try to respect the users custom themes.

At the time the decision was made I don't know that custom themes were considered (although I may be wrong).  Having our own styles allow us to give slightly more branded feel which is nice.  I think we need to do some more investigation into this to determine the best options.

I think for now we should fix this (in the way you described) and file an issue to look into this in the future.  While I think this is important I think a complete change to the theme would be a costly effort for the benefit (as for the future suggestion).

**Comment by amanda-tarafa** [comment]
@iantalarico Agree! Removing themes would be a big task and not easily testable. Also I understand the need for themes for branding.
I will look into removing explicit text colors, maybe backgrounds in they get in the way, and will manually test as much as possible.

**Comment by amanda-tarafa** [comment]
Fixed in #900
