### ISSUE TITLE
The template wizard has no feature radiobutton pre-selected.

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-visualstudio#814]
No radio button is preselected, which means that the user is forced to choose one them. This not the normal behavior for the radiobuttons. We should pre-select one of them, probably the MVC one, so the user can just click through if they choose.

<img width="143" alt="screen shot 2017-10-02 at 1 24 41 pm" src="https://user-images.githubusercontent.com/9807532/31077087-217b8b0e-a775-11e7-8a49-e676c85654d5.png">

**Comment by ILMTitan** [comment]
This was intentional. The user should have to think about what they want. If MVC is preselected, some users will assume the template only creates MVC projects because they didn't read.

**Comment by ivannaranjo** [comment]
But

**Comment by ivannaranjo** [comment]
But the UI looks buggy. Radiobuttons never do this. Even Microsoft's template defaults to "Empty" in their dialog, although they use a different UI control.

The dialog needs to be functional and correct. Can you fix this for 2.1?

**Comment by ivannaranjo** [comment]
We should definitely choose MVC as the default as well, it is the most appropriate project for App Engine Flexible by far, since it is the UI project. Specially while testing out the platform.

**Comment by ILMTitan** [comment]
The [Default Values section of Microsoft's Radio Button Style Guide](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742436%28v=vs.85%29.aspx#Default_values) agrees with you. This is not one if their defined exceptions.
