### ISSUE TITLE
The spacing of the project selection controls is inconsistent with the rest of the UI

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-visualstudio#832]
The `TextBox` is too close to the "Clusters" tag. The problem appears in the App Engine publish step and the GKE step. See below for the how the problem looks in the GKE step.

<img width="519" alt="screen shot 2017-10-20 at 2 18 52 pm" src="https://user-images.githubusercontent.com/9807532/31822775-c9af26ca-b5a1-11e7-8016-bb309e50a74c.png">

**Comment by ILMTitan** [comment]
This was fixed as part of PR #837.
