### ISSUE TITLE
Why can't I deploy a .NET core application to Compute Engine?

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#846]
Sometimes I still want to deploy a .NET core application to IIS.

![image](https://user-images.githubusercontent.com/11778530/32679208-63adb3f8-c61a-11e7-83b5-6b438b92c4fe.png)

**Comment by ivannaranjo** [comment]
Our target for .NET Core is App Engine and GKE.

**Comment by SurferJeffAtGoogle** [comment]
Why can't a someone deploy a .net core app to IIS if they want to?

**Comment by jskeet** [comment]
Does deploying an ASP.NET Core app to IIS involve the same set of steps as deploying a regular ASP.NET app? If it's significantly different, I think it's a reasonable feature request - but also one that's reasonable to deprioritize unless we see a lot of users wanting it.

**Comment by iantalarico** [comment]
@jskeet It is different to deploy an ASP.NET Core app to IIS.  This is a reasonable feature request but is fairly low in the priority list.

**Comment by SurferJeffAtGoogle** [comment]
I've hit this issue.  I saw someone hit this issue while giving a Google Cloud demo at a local meet up, and now we have a stackoverflow user report this issue.  I don't know your full list of priorities, but the fact that we _know_ users are hitting it suggests it warrants some attention.

**Comment by iantalarico** [comment]
@SurferJeffAtGoogle I understand this issue is being hit and it is on our radar.  We will start with adding documentation to mentioned dialog (see #867) and then in the future allow deployment to GCE.
