### ISSUE TITLE
I can instantiate a 1.0 template when the 1.0 runtime is not installed on my machine.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#850]
Split out of https://github.com/GoogleCloudPlatform/google-cloud-visualstudio/issues/847

And when I try to publish, I get this error:

```
Publishing GcpProject2 to Compute Engine.
dotnet publish -o "C:\Users\Jeffrey Rennie\AppData\Local\Temp\jpolqxei.lnu" -c Release
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  GcpProject2 -> C:\Users\Jeffrey Rennie\source\repos\GcpProject2\GcpProject2\bin\Release\netcoreapp2.0\GcpProject2.dll
  It was not possible to find any compatible framework version
  
  The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  
    - Check application dependencies and target a framework version installed at:
  
        \
  
    - Alternatively, install the framework version '1.0.0'.
  
C:\Users\Jeffrey Rennie\source\repos\GcpProject2\GcpProject2\GcpProject2.csproj(24,5): error MSB3073: The command "dotnet bundle" exited with code -2147450749.
Failed to deploy project GcpProject2 to App Engine Flex.
```

**Comment by ivannaranjo** [comment]
We should definitely check that you have a compatible SDK installed on the machine.

**Comment by jlewin** [comment]
Is the .NET Core 1.0 dependency expected on what appears to be a .NET Core 2 project? Is the dependency only in the Publish implementation of the tool?

I been trying to complete the most simple task of constructing a new project in VS2017 15.6.0 from the **ASP.NET on Google Cloud Platform** template, compile, run, deploy. Everything works great up until I try to deploy, at which point I run into the exact error described above. Installing .NET Core 1.0 from the VS installer resolves the issue but is unexpected, ate a ton of time troubleshooting and was hard to track down and resolve. 

Finally, VS no longer installs .NET Core 1.0 when you enable the **.NET Core cross-platform development** workload so out of the box users need to resolve this dependency manually

**Comment by iantalarico** [comment]
@ILMTitan Jim do you have a chance to TAL at this?

**Comment by ILMTitan** [comment]
Will do.

**Comment by ILMTitan** [comment]
It looks like this had to do with https://github.com/madskristensen/BundlerMinifier/issues/292. Updating the BundlerMinifier.Core version seem fixes this.

**Comment by ILMTitan** [comment]
@jlewin  This is fixed for the next version of the extension. For now, update the version of `BundlerMinifier.Core` to `2.6.362`.
