### ISSUE TITLE
Facilitate enabling APIs and pulling down the appropriate NuGet packages

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-visualstudio#86]
There is an opportunity to help users quickly get up to speed developing against our APIs. That would involve using the extension to enable a new API, pull its associated NuGet packages, and provisioning credentials to help them get up to speed.

**Comment by ivannaranjo** [comment]
We have solved the API portion of this, we now check for credentials and enable as necessary. We will be looking at what to do with Nuget packages later.
