### ISSUE TITLE
When publishing to GCP, the tool should provide brief details on how different publish targets differ

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/google-cloud-visualstudio#867]
When publishing to GCP, you can publish to GKE, AppEngine, etc. There should be (at least) tooltip for each button representing publish target that briefly explains why one should choose that option.

I created very basic webapp in C# that exposed 4 APIs via 1 controller, tested it locally, then tried to deploy it to GCP. When you click on “Publish to Google Cloud…”, you get 3 choices:
App Engine Flex
Container Engine
Compute Engine (disabled)

There is no assistance about these options so if you are not familiar with GCP, you may have trouble choosing one.

**Comment by iantalarico** [comment]
Bumping to P1, this seems to be causing a fair amount of confusing and we are getting more signals about it.
