### ISSUE TITLE
GCP Template name is misleading 

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-visualstudio#883]
The name is "ASP.NET on Google Cloud Platform".  If I was trying to create a ASP.NET Core app for GCP I would not click here.  We should consider changing the name or adding a second template.  If we add a second would could default to .net vs .net core

cc: @amanda-tarafa

**Comment by ILMTitan** [comment]
I thought I was being clever, but you are right. It should be two separate templates, like the standard ASP.NET and ASP.NET Core templates are.
