### ISSUE TITLE
Deployment hangs when Container Builder API is not enabled

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/google-cloud-visualstudio#897]
When Container Builder API is not enabled in Google Cloud and you try to deploy an app from Visual Studio extension to Kubernetes on Google Cloud, the deployment hangs with "Deploying to Container Engine.." prompt forever. You cannot cancel the build at this point and Visual Studio is useless until you kill it. 

Stackdriver logs are clear what the problem is:

message:  "Access Not Configured. Container Builder has not been used in project before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudbuild.googleapis.com/overview?project=.. then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."

**Comment by redborian** [comment]
This issue is fixed (by https://github.com/GoogleCloudPlatform/google-cloud-visualstudio/pull/837) and will be part of the next release.
