### ISSUE TITLE
Check that the Usage Statistics Reporting Opt-in/out doc is published after our release.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/google-cloud-visualstudio#901]
Added the correct Usage Statistics Reporting Opt-in/out doc link.
But the doc is not yet live.
Check that the doc is live before releasing or coordinate with Jimmy Park for it to be release soon after.

**Comment by iantalarico** [comment]
bumping to a p1 as I am more likely to see it during a triage :)

**Comment by ILMTitan** [comment]
I can verify the doc is live. Closing.
