### ISSUE TITLE
Flaky test that makes vstest.console.exe crash.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/google-cloud-visualstudio#915]
[Here](https://ci.appveyor.com/project/ivannaranjo/google-cloud-visualstudio-bnnrp/build/1.0.1746-master) is the log for one of the times it has happened, I’ve seen it several others but hasn’t happened either in local or after I started pushing the crash dump as an artifact so it’s hard to diagnose it right now. Curiously, when searching for the exception and message thrown there (System.InvalidOperationException: LocalDataStoreSlot storage has been freed.) I found [this nuget flaky](https://github.com/NuGet/Home/issues/5497) test issue that has to do with trying to set the status of a TaskCompletionSource when it is already in a final state. We use [TaskCompletionSource](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcompletionsource-1?view=netframework-4.5.2) in several tests. We should also look into this, hopefully if it happens again, we’ll have the dump files to determine exactly where.
This one spawned from #906

**Comment by ILMTitan** [comment]
The error in the given test looks similar to the one probably fixed in PR #940. It did not have to do with the TaskCompletionSource, but rather with the shutdown of a WPF component or application. I think we can close this, given PR #940.

**Comment by amanda-tarafa** [comment]
Yep sounds good, I was never able to properly see why this was happening because it was so sporadic and it never happened after I had the dump files pushed as artifacts. Just had the suspisions on `TaskCompletionSource` because of that other thread I found. We can always reopen if something like this happens again. Closing...
