### ISSUE TITLE
Test dependency and mocking of global resources.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/google-cloud-visualstudio#917]
Review usage, test dependency and mocking of global resources in general. This is one of the ways in which we could introduce flakiness more inadvertently, and given that several of the global resources are unmanaged, these problems would be hard to diagnose, they don’t make tests fail, but vstest.console.exe crash.
Spawns from #906.

**Comment by amanda-tarafa** [comment]
For dependencies on Package:

1. Consider creating a `TestBase` class that always mocks `GoogleCloudExtensionPackage.Instance` without setting up any methods but with strict behavior so that it is clear what each test is dependent on.
2. Have helper methods on `TestBase` to set up or mock the `GoogleCloudExtensionPackage` methods that are needed, so that tests can explicitly setup what they need.

Take a look at #929 .

**Comment by ILMTitan** [comment]
Closed in #934
