### ISSUE TITLE
When publishing to GKE, the Refresh Cluster does not work.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/google-cloud-visualstudio#920]
When publishing to GKE, if no clusters exist on the project, and one clicks on the link to Create Cluster, successfully creating one (I waited till it was properly created on Cloud Console), then the Refresh Cluster link does not work. I had to close the dialog and Open it again to see the cluster I had just created.

**Comment by ILMTitan** [comment]
Closed in #956
