### ISSUE TITLE
Publishing a .Net Core MVC application created with VS2017 template (Microsoft's) fails.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/google-cloud-visualstudio#924]
Coming from [this](https://stackoverflow.com/questions/49650029/app-deployment-failed) SO question.

Publishing a .Net Core MVC (2.0) application created with our Google Cloud Templates succeeds and yet publishing a .Net Core MVC (2.0) application created with Microsoft's VS 2017 template fails.

MS Template's are using .Net Core 2.0.6 and ours is using 2.0.0. The error we get is seen on the following screenshot and has to do with a library or its needed version not found on the image we are trying to deploy to.
![image](https://user-images.githubusercontent.com/14878252/38368242-afac1ecc-38dc-11e8-9a0b-96736d84335f.png)

Changing the project file (.csproj) of the MS Template generated project to use .Net Core 2.0.0 fixes the issue

```
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
</ItemGroup>
```

But, in our docs, at least [here](https://cloud.google.com/appengine/docs/flexible/dotnet/quickstart), we say we support .Net Core 2.0, so we should support .Net Core 2.0.6, or change the docs to say we support exactly .Net Core 2.0.0.

I think the Docker image is not supporting .Net Core 2.0.6.

**Comment by iantalarico** [comment]
This is an issue with our runtimes.  We need to add support for 2.0.6 I will do this today.

**Comment by amanda-tarafa** [comment]
Closing in this repo after moving to the aspnet-docker repo which is the correct one.
New issue [here](https://github.com/GoogleCloudPlatform/aspnet-docker/issues/91).
