### ISSUE TITLE
When publishing to Flex, the Pulish button is sometimes enabled even if there is no version specified.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/google-cloud-visualstudio#925]
Reproduce, on the Publish to Flex dialog.

1. Have a valid project (apis and everything enabled) and a valid version number. Publish btn is properly enabled.
2. Delete the version number. Publish btn is properly disabled.
3. Select another valid project. Version is missing. Publish btn is wrongly enabled.

![image](https://user-images.githubusercontent.com/14878252/38379487-bdcec2f4-38f8-11e8-9da8-565632c72911.png)

**Comment by ILMTitan** [comment]
Closed in #956
