### ISSUE TITLE
IIS Rewrite rules not working when published to GCP 

### ISSUE THREAD

**Issue by samgithub-duplicate** [GoogleCloudPlatform/google-cloud-visualstudio#937]
I am publishing to WinServer 2016 Compute Engine.  My redirect rules from HTTP --> HTTPS are not working.  The site still allows HTTP.

Note: HtttRedirect and URL ReWrite 2.1 are installed on the server.  -- See attached files.
![iisconfigurationwinserver2016](https://user-images.githubusercontent.com/731590/38751581-84650a12-3f26-11e8-8228-1da99a779134.png)

![urlrewritemodule](https://user-images.githubusercontent.com/731590/38751592-8df19960-3f26-11e8-8d63-5ba42fcd6dda.png)

My full web-config (from VS2017) is 

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer> 
    <rewrite>
       <rules>
           <rule name="HTTPS Redirect" enabled="true" stopProcessing="true">
               <match url="(.*)" />
           <conditions>
                       <add input="{HTTP_X_FORWARDED_PROTO}" pattern="https" negate="true" />
               </conditions>
           <action type="Redirect" url="https://{HTTP_HOST}/{R:1}" />
           </rule>
       </rules>
   </rewrite>
    <handlers>
      <remove name="aspNetCore"/>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>

Is it possible that the Google Cloud Tools for Visual Studio is not copying web.config to GCP; or GCP is not handling the ASPNetCore IIS Integration?  My Program.cs is setup to use IIS Integration as shown below:

    var host = new WebHostBuilder()
           .UseKestrel()
           .UseContentRoot(Directory.GetCurrentDirectory())
           .UseIISIntegration()
           .UseStartup<Startup>()
           .Build();

            host.Run();

**Comment by iantalarico** [comment]
@samgithub-duplicate Can you provide some more context on how you are deploying?  Google Cloud Tools for Visual Studio should be copying over the web.config.

The extension should only allow deploying ASP.NET applications to GCE not ASP.NET Core.

**Comment by samgithub-duplicate** [comment]
Yes I am using the extension to deploy the web "**application**" (written using ASPNET Core 2  -- very "similar to the "hello world sample."   To deploy, I am right-clicking on the application (in VS)) and selecting "Publish to Google Cloud".  The deployment works and things work when deployed, except for the HTTP --> HTTPS rewrite.

Do you happen to know if anyone has successfully deployed the "Hello World" app, configured IIS in web.config to rewrite all access to HTTPS?

**Comment by samgithub-duplicate** [comment]
A quick way to confirm my issue is to copy the web.config I sent to the hello world app, deploy it and see if it rewrites HTTP ---> HTTPS

I reached out to your team because I am at my wits end, having spent this entire week trying to resolve this.  

Note:  I have  google-managed-certificates (Let's Encrypt) installed.

**Comment by iantalarico** [comment]
@samgithub-duplicate Thanks for the added context.

I'm OOO most of the rest of the week but I will try and look into this more next week.

**Comment by iantalarico** [comment]
@samgithub-duplicate I just did a quick deployment and check the machine after deployment and I am seeing the copied over web.config file.

Can you confirm that the file is actually not being copied over in your case?

Can you send me your http -> https rewrite so I can test it?

**Comment by samgithub-duplicate** [comment]
Here is my web.config:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer> 
    <rewrite>
       <rules>
           <rule name="HTTPS Redirect" enabled="true" stopProcessing="true">
               <match url="(.*)" />
           <conditions>
                       <add input="{HTTP_X_FORWARDED_PROTO}" pattern="https" negate="true" />
               </conditions>
           <action type="Redirect" url="https://{HTTP_HOST}/{R:1}" />
           </rule>
       </rules>
   </rewrite>
    <handlers>
      <remove name="aspNetCore"/>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>

**Comment by samgithub-duplicate** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer> 
    <rewrite>
       <rules>
           <rule name="HTTPS Redirect" enabled="true" stopProcessing="true">
               <match url="(.*)" />
           <conditions>
                       <add input="{HTTP_X_FORWARDED_PROTO}" pattern="https" negate="true" />
               </conditions>
           <action type="Redirect" url="https://{HTTP_HOST}/{R:1}" />
           </rule>
       </rules>
   </rewrite>
    <handlers>
      <remove name="aspNetCore"/>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>

**Comment by samgithub-duplicate** [comment]
[webconfigWithURLRewrite.txt](https://github.com/GoogleCloudPlatform/google-cloud-visualstudio/files/1943196/webconfigWithURLRewrite.txt)

**Comment by iantalarico** [comment]
@samgithub-duplicate It looks like these files are being copied over.  This doesn't seem to be an issue with the extension.

My best guess is this is an issue with SSL certs.  Have you installed/configured them on this machine?

If you are still having issues it may be worth [contacting support](https://cloud.google.com/support)
