### ISSUE TITLE
On the GCE publish dialog, add a link to refresh instances.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/google-cloud-visualstudio#938]
When publishing to GCE, the user either selects an existing instance or might want to create a new one. For this, the user goes to the Web Cloud Console, which is OK, but we don't have a straightforward mechanism for the user to refresh the dialog with the instances they have created, they need to close the dialog an open it again or reselect the project from the project selector, which is not intuitive.

![image](https://user-images.githubusercontent.com/14878252/38878775-a7a40722-4259-11e8-844a-04d5d936a83a.png)

**Comment by ILMTitan** [comment]
@amanda-tarafa Is this part of PR #935, or should we push this issue to the 2.0.0 milestone?

**Comment by ILMTitan** [comment]
Closed in #960
