### ISSUE TITLE
Display or Set the AppEngine Service the deploy is targeting.

### ISSUE THREAD

**Issue by ILMTitan** [GoogleCloudPlatform/google-cloud-visualstudio#947]
Enable deploying to services other than the default service.

**Comment by iantalarico** [comment]
IIRC this has to be done in the app.yaml file (but I may be wrong).  do you know if this is the case?  Will we modify the app.yaml file?

**Comment by ILMTitan** [comment]
Oh, right. We shouldn't do that, but we should display the service being deployed to, and give a help icon to tell the user where the value is coming from.

**Comment by ILMTitan** [comment]
In the case where the project does not have an app.yaml already, the extension creates one. We should provide changing the service as an option on that app.yaml.
